package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for addiecexchange kernel
var addiecexchange_code cu.Function

// Stores the arguments for addiecexchange kernel invocation
type addiecexchange_args_t struct {
	arg_Bx      unsafe.Pointer
	arg_By      unsafe.Pointer
	arg_Bz      unsafe.Pointer
	arg_mx      unsafe.Pointer
	arg_my      unsafe.Pointer
	arg_mz      unsafe.Pointer
	arg_j1LUT2d unsafe.Pointer
	arg_j2LUT2d unsafe.Pointer
	arg_regions unsafe.Pointer
	arg_wx      float32
	arg_wy      float32
	arg_wz      float32
	arg_Nx      int
	arg_Ny      int
	arg_Nz      int
	arg_PBC     byte
	argptr      [16]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for addiecexchange kernel invocation
var addiecexchange_args addiecexchange_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	addiecexchange_args.argptr[0] = unsafe.Pointer(&addiecexchange_args.arg_Bx)
	addiecexchange_args.argptr[1] = unsafe.Pointer(&addiecexchange_args.arg_By)
	addiecexchange_args.argptr[2] = unsafe.Pointer(&addiecexchange_args.arg_Bz)
	addiecexchange_args.argptr[3] = unsafe.Pointer(&addiecexchange_args.arg_mx)
	addiecexchange_args.argptr[4] = unsafe.Pointer(&addiecexchange_args.arg_my)
	addiecexchange_args.argptr[5] = unsafe.Pointer(&addiecexchange_args.arg_mz)
	addiecexchange_args.argptr[6] = unsafe.Pointer(&addiecexchange_args.arg_j1LUT2d)
	addiecexchange_args.argptr[7] = unsafe.Pointer(&addiecexchange_args.arg_j2LUT2d)
	addiecexchange_args.argptr[8] = unsafe.Pointer(&addiecexchange_args.arg_regions)
	addiecexchange_args.argptr[9] = unsafe.Pointer(&addiecexchange_args.arg_wx)
	addiecexchange_args.argptr[10] = unsafe.Pointer(&addiecexchange_args.arg_wy)
	addiecexchange_args.argptr[11] = unsafe.Pointer(&addiecexchange_args.arg_wz)
	addiecexchange_args.argptr[12] = unsafe.Pointer(&addiecexchange_args.arg_Nx)
	addiecexchange_args.argptr[13] = unsafe.Pointer(&addiecexchange_args.arg_Ny)
	addiecexchange_args.argptr[14] = unsafe.Pointer(&addiecexchange_args.arg_Nz)
	addiecexchange_args.argptr[15] = unsafe.Pointer(&addiecexchange_args.arg_PBC)
}

// Wrapper for addiecexchange CUDA kernel, asynchronous.
func k_addiecexchange_async(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, j1LUT2d unsafe.Pointer, j2LUT2d unsafe.Pointer, regions unsafe.Pointer, wx float32, wy float32, wz float32, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("addiecexchange")
	}

	addiecexchange_args.Lock()
	defer addiecexchange_args.Unlock()

	if addiecexchange_code == 0 {
		addiecexchange_code = fatbinLoad(addiecexchange_map, "addiecexchange")
	}

	addiecexchange_args.arg_Bx = Bx
	addiecexchange_args.arg_By = By
	addiecexchange_args.arg_Bz = Bz
	addiecexchange_args.arg_mx = mx
	addiecexchange_args.arg_my = my
	addiecexchange_args.arg_mz = mz
	addiecexchange_args.arg_j1LUT2d = j1LUT2d
	addiecexchange_args.arg_j2LUT2d = j2LUT2d
	addiecexchange_args.arg_regions = regions
	addiecexchange_args.arg_wx = wx
	addiecexchange_args.arg_wy = wy
	addiecexchange_args.arg_wz = wz
	addiecexchange_args.arg_Nx = Nx
	addiecexchange_args.arg_Ny = Ny
	addiecexchange_args.arg_Nz = Nz
	addiecexchange_args.arg_PBC = PBC

	args := addiecexchange_args.argptr[:]
	cu.LaunchKernel(addiecexchange_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("addiecexchange")
	}
}

// maps compute capability on PTX code for addiecexchange kernel.
var addiecexchange_map = map[int]string{0: "",
	20: addiecexchange_ptx_20,
	30: addiecexchange_ptx_30,
	35: addiecexchange_ptx_35,
	50: addiecexchange_ptx_50}

// addiecexchange PTX code for various compute capabilities.
const (
	addiecexchange_ptx_20 = `
.version 4.1
.target sm_20
.address_size 64


.visible .entry addiecexchange(
	.param .u64 addiecexchange_param_0,
	.param .u64 addiecexchange_param_1,
	.param .u64 addiecexchange_param_2,
	.param .u64 addiecexchange_param_3,
	.param .u64 addiecexchange_param_4,
	.param .u64 addiecexchange_param_5,
	.param .u64 addiecexchange_param_6,
	.param .u64 addiecexchange_param_7,
	.param .u64 addiecexchange_param_8,
	.param .f32 addiecexchange_param_9,
	.param .f32 addiecexchange_param_10,
	.param .f32 addiecexchange_param_11,
	.param .u32 addiecexchange_param_12,
	.param .u32 addiecexchange_param_13,
	.param .u32 addiecexchange_param_14,
	.param .u8 addiecexchange_param_15
)
{
	.reg .pred 	%p<14>;
	.reg .s16 	%rs<7>;
	.reg .s32 	%r<168>;
	.reg .f32 	%f<106>;
	.reg .s64 	%rd<124>;


	ld.param.u64 	%rd1, [addiecexchange_param_0];
	ld.param.u64 	%rd2, [addiecexchange_param_1];
	ld.param.u64 	%rd3, [addiecexchange_param_2];
	ld.param.u64 	%rd4, [addiecexchange_param_3];
	ld.param.u64 	%rd5, [addiecexchange_param_4];
	ld.param.u64 	%rd6, [addiecexchange_param_5];
	ld.param.u64 	%rd7, [addiecexchange_param_6];
	ld.param.u64 	%rd8, [addiecexchange_param_7];
	ld.param.u64 	%rd9, [addiecexchange_param_8];
	ld.param.f32 	%f31, [addiecexchange_param_9];
	ld.param.f32 	%f32, [addiecexchange_param_10];
	ld.param.f32 	%f33, [addiecexchange_param_11];
	ld.param.u32 	%r30, [addiecexchange_param_12];
	ld.param.u32 	%r31, [addiecexchange_param_13];
	ld.param.u32 	%r32, [addiecexchange_param_14];
	ld.param.u8 	%rs4, [addiecexchange_param_15];
	mov.u32 	%r33, %ntid.x;
	mov.u32 	%r34, %ctaid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mov.u32 	%r36, %ntid.y;
	mov.u32 	%r37, %ctaid.y;
	mov.u32 	%r38, %tid.y;
	mad.lo.s32 	%r2, %r36, %r37, %r38;
	mov.u32 	%r39, %ntid.z;
	mov.u32 	%r40, %ctaid.z;
	mov.u32 	%r41, %tid.z;
	mad.lo.s32 	%r3, %r39, %r40, %r41;
	setp.ge.s32	%p1, %r2, %r31;
	setp.ge.s32	%p2, %r1, %r30;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32	%p4, %r3, %r32;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_23;

	cvta.to.global.u64 	%rd10, %rd6;
	mad.lo.s32 	%r42, %r3, %r31, %r2;
	mul.lo.s32 	%r4, %r42, %r30;
	add.s32 	%r43, %r4, %r1;
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r43, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvta.to.global.u64 	%rd14, %rd5;
	add.s64 	%rd15, %rd14, %rd12;
	add.s64 	%rd16, %rd10, %rd12;
	ld.global.f32 	%f1, [%rd13];
	ld.global.f32 	%f2, [%rd15];
	mul.f32 	%f34, %f2, %f2;
	fma.rn.f32 	%f35, %f1, %f1, %f34;
	ld.global.f32 	%f3, [%rd16];
	fma.rn.f32 	%f36, %f3, %f3, %f35;
	setp.eq.f32	%p6, %f36, 0f00000000;
	@%p6 bra 	BB0_23;

	cvta.to.global.u64 	%rd17, %rd9;
	mad.lo.s32 	%r49, %r42, %r30, %r1;
	cvt.s64.s32	%rd18, %r49;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.u8 	%r5, [%rd19];
	cvta.to.global.u64 	%rd20, %rd1;
	mul.wide.s32 	%rd21, %r49, 4;
	add.s64 	%rd22, %rd20, %rd21;
	ld.global.f32 	%f4, [%rd22];
	cvta.to.global.u64 	%rd23, %rd2;
	add.s64 	%rd24, %rd23, %rd21;
	ld.global.f32 	%f5, [%rd24];
	cvta.to.global.u64 	%rd25, %rd3;
	add.s64 	%rd26, %rd25, %rd21;
	ld.global.f32 	%f6, [%rd26];
	add.s32 	%r6, %r1, -1;
	and.b16  	%rs1, %rs4, 1;
	setp.eq.b16	%p7, %rs1, 1;
	@!%p7 bra 	BB0_4;
	bra.uni 	BB0_3;

BB0_3:
	rem.s32 	%r50, %r6, %r30;
	add.s32 	%r51, %r50, %r30;
	rem.s32 	%r162, %r51, %r30;
	bra.uni 	BB0_5;

BB0_4:
	mov.u32 	%r52, 0;
	max.s32 	%r162, %r6, %r52;

BB0_5:
	add.s32 	%r53, %r162, %r4;
	cvt.s64.s32	%rd28, %r53;
	mul.wide.s32 	%rd30, %r53, 4;
	add.s64 	%rd31, %rd11, %rd30;
	add.s64 	%rd33, %rd14, %rd30;
	add.s64 	%rd35, %rd10, %rd30;
	add.s64 	%rd36, %rd17, %rd28;
	ld.global.u8 	%r54, [%rd36];
	shl.b32 	%r55, %r54, 8;
	add.s32 	%r56, %r55, %r5;
	cvta.to.global.u64 	%rd37, %rd7;
	mul.wide.s32 	%rd38, %r56, 4;
	add.s64 	%rd39, %rd37, %rd38;
	cvta.to.global.u64 	%rd40, %rd8;
	add.s64 	%rd41, %rd40, %rd38;
	ld.global.f32 	%f37, [%rd41];
	add.f32 	%f38, %f37, %f37;
	ld.global.f32 	%f39, [%rd31];
	ld.global.f32 	%f40, [%rd33];
	mul.f32 	%f41, %f40, %f2;
	fma.rn.f32 	%f42, %f39, %f1, %f41;
	ld.global.f32 	%f43, [%rd35];
	fma.rn.f32 	%f44, %f43, %f3, %f42;
	ld.global.f32 	%f45, [%rd39];
	fma.rn.f32 	%f46, %f38, %f44, %f45;
	add.f32 	%f7, %f31, %f31;
	mul.f32 	%f47, %f7, %f46;
	fma.rn.f32 	%f8, %f47, %f39, %f4;
	fma.rn.f32 	%f9, %f47, %f40, %f5;
	fma.rn.f32 	%f10, %f47, %f43, %f6;
	add.s32 	%r10, %r1, 1;
	setp.eq.s16	%p8, %rs1, 0;
	@%p8 bra 	BB0_7;

	rem.s32 	%r61, %r10, %r30;
	add.s32 	%r62, %r61, %r30;
	rem.s32 	%r163, %r62, %r30;
	bra.uni 	BB0_8;

BB0_7:
	add.s32 	%r63, %r30, -1;
	min.s32 	%r163, %r10, %r63;

BB0_8:
	add.s32 	%r64, %r163, %r4;
	cvt.s64.s32	%rd43, %r64;
	mul.wide.s32 	%rd45, %r64, 4;
	add.s64 	%rd46, %rd11, %rd45;
	add.s64 	%rd48, %rd14, %rd45;
	add.s64 	%rd50, %rd10, %rd45;
	add.s64 	%rd51, %rd17, %rd43;
	ld.global.u8 	%r65, [%rd51];
	shl.b32 	%r66, %r65, 8;
	add.s32 	%r67, %r66, %r5;
	mul.wide.s32 	%rd53, %r67, 4;
	add.s64 	%rd54, %rd37, %rd53;
	add.s64 	%rd56, %rd40, %rd53;
	ld.global.f32 	%f48, [%rd56];
	add.f32 	%f49, %f48, %f48;
	ld.global.f32 	%f50, [%rd46];
	ld.global.f32 	%f51, [%rd48];
	mul.f32 	%f52, %f51, %f2;
	fma.rn.f32 	%f53, %f50, %f1, %f52;
	ld.global.f32 	%f54, [%rd50];
	fma.rn.f32 	%f55, %f54, %f3, %f53;
	ld.global.f32 	%f56, [%rd54];
	fma.rn.f32 	%f57, %f49, %f55, %f56;
	mul.f32 	%f58, %f7, %f57;
	fma.rn.f32 	%f11, %f58, %f50, %f8;
	fma.rn.f32 	%f12, %f58, %f51, %f9;
	fma.rn.f32 	%f13, %f58, %f54, %f10;
	and.b16  	%rs2, %rs4, 2;
	setp.eq.s16	%p9, %rs2, 0;
	add.s32 	%r14, %r2, -1;
	@%p9 bra 	BB0_10;

	rem.s32 	%r72, %r14, %r31;
	add.s32 	%r73, %r72, %r31;
	rem.s32 	%r164, %r73, %r31;
	bra.uni 	BB0_11;

BB0_10:
	mov.u32 	%r74, 0;
	max.s32 	%r164, %r14, %r74;

BB0_11:
	mad.lo.s32 	%r79, %r3, %r31, %r164;
	mad.lo.s32 	%r84, %r79, %r30, %r1;
	cvt.s64.s32	%rd58, %r84;
	mul.wide.s32 	%rd60, %r84, 4;
	add.s64 	%rd61, %rd11, %rd60;
	add.s64 	%rd63, %rd14, %rd60;
	add.s64 	%rd65, %rd10, %rd60;
	add.s64 	%rd66, %rd17, %rd58;
	ld.global.u8 	%r85, [%rd66];
	shl.b32 	%r86, %r85, 8;
	add.s32 	%r87, %r86, %r5;
	mul.wide.s32 	%rd68, %r87, 4;
	add.s64 	%rd69, %rd37, %rd68;
	add.s64 	%rd71, %rd40, %rd68;
	ld.global.f32 	%f59, [%rd71];
	add.f32 	%f60, %f59, %f59;
	ld.global.f32 	%f61, [%rd61];
	ld.global.f32 	%f62, [%rd63];
	mul.f32 	%f63, %f62, %f2;
	fma.rn.f32 	%f64, %f61, %f1, %f63;
	ld.global.f32 	%f65, [%rd65];
	fma.rn.f32 	%f66, %f65, %f3, %f64;
	ld.global.f32 	%f67, [%rd69];
	fma.rn.f32 	%f68, %f60, %f66, %f67;
	add.f32 	%f14, %f32, %f32;
	mul.f32 	%f69, %f14, %f68;
	fma.rn.f32 	%f15, %f69, %f61, %f11;
	fma.rn.f32 	%f16, %f69, %f62, %f12;
	fma.rn.f32 	%f17, %f69, %f65, %f13;
	add.s32 	%r18, %r2, 1;
	and.b16  	%rs5, %rs2, 255;
	setp.eq.s16	%p10, %rs5, 0;
	@%p10 bra 	BB0_13;

	rem.s32 	%r92, %r18, %r31;
	add.s32 	%r93, %r92, %r31;
	rem.s32 	%r165, %r93, %r31;
	bra.uni 	BB0_14;

BB0_13:
	add.s32 	%r94, %r31, -1;
	min.s32 	%r165, %r18, %r94;

BB0_14:
	mad.lo.s32 	%r99, %r3, %r31, %r165;
	mad.lo.s32 	%r104, %r99, %r30, %r1;
	cvt.s64.s32	%rd73, %r104;
	mul.wide.s32 	%rd75, %r104, 4;
	add.s64 	%rd76, %rd11, %rd75;
	add.s64 	%rd78, %rd14, %rd75;
	add.s64 	%rd80, %rd10, %rd75;
	add.s64 	%rd81, %rd17, %rd73;
	ld.global.u8 	%r105, [%rd81];
	shl.b32 	%r106, %r105, 8;
	add.s32 	%r107, %r106, %r5;
	mul.wide.s32 	%rd83, %r107, 4;
	add.s64 	%rd84, %rd37, %rd83;
	add.s64 	%rd86, %rd40, %rd83;
	ld.global.f32 	%f70, [%rd86];
	add.f32 	%f71, %f70, %f70;
	ld.global.f32 	%f72, [%rd76];
	ld.global.f32 	%f73, [%rd78];
	mul.f32 	%f74, %f73, %f2;
	fma.rn.f32 	%f75, %f72, %f1, %f74;
	ld.global.f32 	%f76, [%rd80];
	fma.rn.f32 	%f77, %f76, %f3, %f75;
	ld.global.f32 	%f78, [%rd84];
	fma.rn.f32 	%f79, %f71, %f77, %f78;
	mul.f32 	%f80, %f14, %f79;
	fma.rn.f32 	%f103, %f80, %f72, %f15;
	fma.rn.f32 	%f104, %f80, %f73, %f16;
	fma.rn.f32 	%f105, %f80, %f76, %f17;
	setp.eq.s32	%p11, %r32, 1;
	@%p11 bra 	BB0_22;

	and.b16  	%rs3, %rs4, 4;
	setp.eq.s16	%p12, %rs3, 0;
	add.s32 	%r22, %r3, -1;
	@%p12 bra 	BB0_17;

	rem.s32 	%r112, %r22, %r32;
	add.s32 	%r113, %r112, %r32;
	rem.s32 	%r166, %r113, %r32;
	bra.uni 	BB0_18;

BB0_17:
	mov.u32 	%r114, 0;
	max.s32 	%r166, %r22, %r114;

BB0_18:
	mad.lo.s32 	%r119, %r166, %r31, %r2;
	mad.lo.s32 	%r124, %r119, %r30, %r1;
	cvt.s64.s32	%rd88, %r124;
	mul.wide.s32 	%rd90, %r124, 4;
	add.s64 	%rd91, %rd11, %rd90;
	add.s64 	%rd93, %rd14, %rd90;
	add.s64 	%rd95, %rd10, %rd90;
	add.s64 	%rd96, %rd17, %rd88;
	ld.global.u8 	%r125, [%rd96];
	shl.b32 	%r126, %r125, 8;
	add.s32 	%r127, %r126, %r5;
	mul.wide.s32 	%rd98, %r127, 4;
	add.s64 	%rd99, %rd37, %rd98;
	add.s64 	%rd101, %rd40, %rd98;
	ld.global.f32 	%f81, [%rd101];
	add.f32 	%f82, %f81, %f81;
	ld.global.f32 	%f83, [%rd91];
	ld.global.f32 	%f84, [%rd93];
	mul.f32 	%f85, %f84, %f2;
	fma.rn.f32 	%f86, %f83, %f1, %f85;
	ld.global.f32 	%f87, [%rd95];
	fma.rn.f32 	%f88, %f87, %f3, %f86;
	ld.global.f32 	%f89, [%rd99];
	fma.rn.f32 	%f90, %f82, %f88, %f89;
	add.f32 	%f21, %f33, %f33;
	mul.f32 	%f91, %f21, %f90;
	fma.rn.f32 	%f22, %f91, %f83, %f103;
	fma.rn.f32 	%f23, %f91, %f84, %f104;
	fma.rn.f32 	%f24, %f91, %f87, %f105;
	add.s32 	%r26, %r3, 1;
	and.b16  	%rs6, %rs3, 255;
	setp.eq.s16	%p13, %rs6, 0;
	@%p13 bra 	BB0_20;

	rem.s32 	%r132, %r26, %r32;
	add.s32 	%r133, %r132, %r32;
	rem.s32 	%r167, %r133, %r32;
	bra.uni 	BB0_21;

BB0_20:
	add.s32 	%r134, %r32, -1;
	min.s32 	%r167, %r26, %r134;

BB0_21:
	mad.lo.s32 	%r139, %r167, %r31, %r2;
	mad.lo.s32 	%r144, %r139, %r30, %r1;
	cvt.s64.s32	%rd103, %r144;
	mul.wide.s32 	%rd105, %r144, 4;
	add.s64 	%rd106, %rd11, %rd105;
	add.s64 	%rd108, %rd14, %rd105;
	add.s64 	%rd110, %rd10, %rd105;
	add.s64 	%rd111, %rd17, %rd103;
	ld.global.u8 	%r145, [%rd111];
	shl.b32 	%r146, %r145, 8;
	add.s32 	%r147, %r146, %r5;
	mul.wide.s32 	%rd113, %r147, 4;
	add.s64 	%rd114, %rd37, %rd113;
	add.s64 	%rd116, %rd40, %rd113;
	ld.global.f32 	%f92, [%rd116];
	add.f32 	%f93, %f92, %f92;
	ld.global.f32 	%f94, [%rd106];
	ld.global.f32 	%f95, [%rd108];
	mul.f32 	%f96, %f95, %f2;
	fma.rn.f32 	%f97, %f94, %f1, %f96;
	ld.global.f32 	%f98, [%rd110];
	fma.rn.f32 	%f99, %f98, %f3, %f97;
	ld.global.f32 	%f100, [%rd114];
	fma.rn.f32 	%f101, %f93, %f99, %f100;
	mul.f32 	%f102, %f21, %f101;
	fma.rn.f32 	%f103, %f102, %f94, %f22;
	fma.rn.f32 	%f104, %f102, %f95, %f23;
	fma.rn.f32 	%f105, %f102, %f98, %f24;

BB0_22:
	mul.wide.s32 	%rd118, %r49, 4;
	add.s64 	%rd119, %rd20, %rd118;
	st.global.f32 	[%rd119], %f103;
	add.s64 	%rd121, %rd23, %rd118;
	st.global.f32 	[%rd121], %f104;
	add.s64 	%rd123, %rd25, %rd118;
	st.global.f32 	[%rd123], %f105;

BB0_23:
	ret;
}


`
	addiecexchange_ptx_30 = `
.version 4.1
.target sm_30
.address_size 64


.visible .entry addiecexchange(
	.param .u64 addiecexchange_param_0,
	.param .u64 addiecexchange_param_1,
	.param .u64 addiecexchange_param_2,
	.param .u64 addiecexchange_param_3,
	.param .u64 addiecexchange_param_4,
	.param .u64 addiecexchange_param_5,
	.param .u64 addiecexchange_param_6,
	.param .u64 addiecexchange_param_7,
	.param .u64 addiecexchange_param_8,
	.param .f32 addiecexchange_param_9,
	.param .f32 addiecexchange_param_10,
	.param .f32 addiecexchange_param_11,
	.param .u32 addiecexchange_param_12,
	.param .u32 addiecexchange_param_13,
	.param .u32 addiecexchange_param_14,
	.param .u8 addiecexchange_param_15
)
{
	.reg .pred 	%p<14>;
	.reg .s16 	%rs<7>;
	.reg .s32 	%r<168>;
	.reg .f32 	%f<106>;
	.reg .s64 	%rd<124>;


	ld.param.u64 	%rd1, [addiecexchange_param_0];
	ld.param.u64 	%rd2, [addiecexchange_param_1];
	ld.param.u64 	%rd3, [addiecexchange_param_2];
	ld.param.u64 	%rd4, [addiecexchange_param_3];
	ld.param.u64 	%rd5, [addiecexchange_param_4];
	ld.param.u64 	%rd6, [addiecexchange_param_5];
	ld.param.u64 	%rd7, [addiecexchange_param_6];
	ld.param.u64 	%rd8, [addiecexchange_param_7];
	ld.param.u64 	%rd9, [addiecexchange_param_8];
	ld.param.f32 	%f31, [addiecexchange_param_9];
	ld.param.f32 	%f32, [addiecexchange_param_10];
	ld.param.f32 	%f33, [addiecexchange_param_11];
	ld.param.u32 	%r30, [addiecexchange_param_12];
	ld.param.u32 	%r31, [addiecexchange_param_13];
	ld.param.u32 	%r32, [addiecexchange_param_14];
	ld.param.u8 	%rs4, [addiecexchange_param_15];
	mov.u32 	%r33, %ntid.x;
	mov.u32 	%r34, %ctaid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r33, %r34, %r35;
	mov.u32 	%r36, %ntid.y;
	mov.u32 	%r37, %ctaid.y;
	mov.u32 	%r38, %tid.y;
	mad.lo.s32 	%r2, %r36, %r37, %r38;
	mov.u32 	%r39, %ntid.z;
	mov.u32 	%r40, %ctaid.z;
	mov.u32 	%r41, %tid.z;
	mad.lo.s32 	%r3, %r39, %r40, %r41;
	setp.ge.s32	%p1, %r2, %r31;
	setp.ge.s32	%p2, %r1, %r30;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32	%p4, %r3, %r32;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_23;

	cvta.to.global.u64 	%rd10, %rd6;
	mad.lo.s32 	%r42, %r3, %r31, %r2;
	mul.lo.s32 	%r4, %r42, %r30;
	add.s32 	%r43, %r4, %r1;
	cvta.to.global.u64 	%rd11, %rd4;
	mul.wide.s32 	%rd12, %r43, 4;
	add.s64 	%rd13, %rd11, %rd12;
	cvta.to.global.u64 	%rd14, %rd5;
	add.s64 	%rd15, %rd14, %rd12;
	add.s64 	%rd16, %rd10, %rd12;
	ld.global.f32 	%f1, [%rd13];
	ld.global.f32 	%f2, [%rd15];
	mul.f32 	%f34, %f2, %f2;
	fma.rn.f32 	%f35, %f1, %f1, %f34;
	ld.global.f32 	%f3, [%rd16];
	fma.rn.f32 	%f36, %f3, %f3, %f35;
	setp.eq.f32	%p6, %f36, 0f00000000;
	@%p6 bra 	BB0_23;

	cvta.to.global.u64 	%rd17, %rd9;
	mad.lo.s32 	%r49, %r42, %r30, %r1;
	cvt.s64.s32	%rd18, %r49;
	add.s64 	%rd19, %rd17, %rd18;
	ld.global.u8 	%r5, [%rd19];
	cvta.to.global.u64 	%rd20, %rd1;
	mul.wide.s32 	%rd21, %r49, 4;
	add.s64 	%rd22, %rd20, %rd21;
	ld.global.f32 	%f4, [%rd22];
	cvta.to.global.u64 	%rd23, %rd2;
	add.s64 	%rd24, %rd23, %rd21;
	ld.global.f32 	%f5, [%rd24];
	cvta.to.global.u64 	%rd25, %rd3;
	add.s64 	%rd26, %rd25, %rd21;
	ld.global.f32 	%f6, [%rd26];
	add.s32 	%r6, %r1, -1;
	and.b16  	%rs1, %rs4, 1;
	setp.eq.b16	%p7, %rs1, 1;
	@!%p7 bra 	BB0_4;
	bra.uni 	BB0_3;

BB0_3:
	rem.s32 	%r50, %r6, %r30;
	add.s32 	%r51, %r50, %r30;
	rem.s32 	%r162, %r51, %r30;
	bra.uni 	BB0_5;

BB0_4:
	mov.u32 	%r52, 0;
	max.s32 	%r162, %r6, %r52;

BB0_5:
	add.s32 	%r53, %r162, %r4;
	cvt.s64.s32	%rd28, %r53;
	mul.wide.s32 	%rd30, %r53, 4;
	add.s64 	%rd31, %rd11, %rd30;
	add.s64 	%rd33, %rd14, %rd30;
	add.s64 	%rd35, %rd10, %rd30;
	add.s64 	%rd36, %rd17, %rd28;
	ld.global.u8 	%r54, [%rd36];
	shl.b32 	%r55, %r54, 8;
	add.s32 	%r56, %r55, %r5;
	cvta.to.global.u64 	%rd37, %rd7;
	mul.wide.s32 	%rd38, %r56, 4;
	add.s64 	%rd39, %rd37, %rd38;
	cvta.to.global.u64 	%rd40, %rd8;
	add.s64 	%rd41, %rd40, %rd38;
	ld.global.f32 	%f37, [%rd41];
	add.f32 	%f38, %f37, %f37;
	ld.global.f32 	%f39, [%rd31];
	ld.global.f32 	%f40, [%rd33];
	mul.f32 	%f41, %f40, %f2;
	fma.rn.f32 	%f42, %f39, %f1, %f41;
	ld.global.f32 	%f43, [%rd35];
	fma.rn.f32 	%f44, %f43, %f3, %f42;
	ld.global.f32 	%f45, [%rd39];
	fma.rn.f32 	%f46, %f38, %f44, %f45;
	add.f32 	%f7, %f31, %f31;
	mul.f32 	%f47, %f7, %f46;
	fma.rn.f32 	%f8, %f47, %f39, %f4;
	fma.rn.f32 	%f9, %f47, %f40, %f5;
	fma.rn.f32 	%f10, %f47, %f43, %f6;
	add.s32 	%r10, %r1, 1;
	setp.eq.s16	%p8, %rs1, 0;
	@%p8 bra 	BB0_7;

	rem.s32 	%r61, %r10, %r30;
	add.s32 	%r62, %r61, %r30;
	rem.s32 	%r163, %r62, %r30;
	bra.uni 	BB0_8;

BB0_7:
	add.s32 	%r63, %r30, -1;
	min.s32 	%r163, %r10, %r63;

BB0_8:
	add.s32 	%r64, %r163, %r4;
	cvt.s64.s32	%rd43, %r64;
	mul.wide.s32 	%rd45, %r64, 4;
	add.s64 	%rd46, %rd11, %rd45;
	add.s64 	%rd48, %rd14, %rd45;
	add.s64 	%rd50, %rd10, %rd45;
	add.s64 	%rd51, %rd17, %rd43;
	ld.global.u8 	%r65, [%rd51];
	shl.b32 	%r66, %r65, 8;
	add.s32 	%r67, %r66, %r5;
	mul.wide.s32 	%rd53, %r67, 4;
	add.s64 	%rd54, %rd37, %rd53;
	add.s64 	%rd56, %rd40, %rd53;
	ld.global.f32 	%f48, [%rd56];
	add.f32 	%f49, %f48, %f48;
	ld.global.f32 	%f50, [%rd46];
	ld.global.f32 	%f51, [%rd48];
	mul.f32 	%f52, %f51, %f2;
	fma.rn.f32 	%f53, %f50, %f1, %f52;
	ld.global.f32 	%f54, [%rd50];
	fma.rn.f32 	%f55, %f54, %f3, %f53;
	ld.global.f32 	%f56, [%rd54];
	fma.rn.f32 	%f57, %f49, %f55, %f56;
	mul.f32 	%f58, %f7, %f57;
	fma.rn.f32 	%f11, %f58, %f50, %f8;
	fma.rn.f32 	%f12, %f58, %f51, %f9;
	fma.rn.f32 	%f13, %f58, %f54, %f10;
	and.b16  	%rs2, %rs4, 2;
	setp.eq.s16	%p9, %rs2, 0;
	add.s32 	%r14, %r2, -1;
	@%p9 bra 	BB0_10;

	rem.s32 	%r72, %r14, %r31;
	add.s32 	%r73, %r72, %r31;
	rem.s32 	%r164, %r73, %r31;
	bra.uni 	BB0_11;

BB0_10:
	mov.u32 	%r74, 0;
	max.s32 	%r164, %r14, %r74;

BB0_11:
	mad.lo.s32 	%r79, %r3, %r31, %r164;
	mad.lo.s32 	%r84, %r79, %r30, %r1;
	cvt.s64.s32	%rd58, %r84;
	mul.wide.s32 	%rd60, %r84, 4;
	add.s64 	%rd61, %rd11, %rd60;
	add.s64 	%rd63, %rd14, %rd60;
	add.s64 	%rd65, %rd10, %rd60;
	add.s64 	%rd66, %rd17, %rd58;
	ld.global.u8 	%r85, [%rd66];
	shl.b32 	%r86, %r85, 8;
	add.s32 	%r87, %r86, %r5;
	mul.wide.s32 	%rd68, %r87, 4;
	add.s64 	%rd69, %rd37, %rd68;
	add.s64 	%rd71, %rd40, %rd68;
	ld.global.f32 	%f59, [%rd71];
	add.f32 	%f60, %f59, %f59;
	ld.global.f32 	%f61, [%rd61];
	ld.global.f32 	%f62, [%rd63];
	mul.f32 	%f63, %f62, %f2;
	fma.rn.f32 	%f64, %f61, %f1, %f63;
	ld.global.f32 	%f65, [%rd65];
	fma.rn.f32 	%f66, %f65, %f3, %f64;
	ld.global.f32 	%f67, [%rd69];
	fma.rn.f32 	%f68, %f60, %f66, %f67;
	add.f32 	%f14, %f32, %f32;
	mul.f32 	%f69, %f14, %f68;
	fma.rn.f32 	%f15, %f69, %f61, %f11;
	fma.rn.f32 	%f16, %f69, %f62, %f12;
	fma.rn.f32 	%f17, %f69, %f65, %f13;
	add.s32 	%r18, %r2, 1;
	and.b16  	%rs5, %rs2, 255;
	setp.eq.s16	%p10, %rs5, 0;
	@%p10 bra 	BB0_13;

	rem.s32 	%r92, %r18, %r31;
	add.s32 	%r93, %r92, %r31;
	rem.s32 	%r165, %r93, %r31;
	bra.uni 	BB0_14;

BB0_13:
	add.s32 	%r94, %r31, -1;
	min.s32 	%r165, %r18, %r94;

BB0_14:
	mad.lo.s32 	%r99, %r3, %r31, %r165;
	mad.lo.s32 	%r104, %r99, %r30, %r1;
	cvt.s64.s32	%rd73, %r104;
	mul.wide.s32 	%rd75, %r104, 4;
	add.s64 	%rd76, %rd11, %rd75;
	add.s64 	%rd78, %rd14, %rd75;
	add.s64 	%rd80, %rd10, %rd75;
	add.s64 	%rd81, %rd17, %rd73;
	ld.global.u8 	%r105, [%rd81];
	shl.b32 	%r106, %r105, 8;
	add.s32 	%r107, %r106, %r5;
	mul.wide.s32 	%rd83, %r107, 4;
	add.s64 	%rd84, %rd37, %rd83;
	add.s64 	%rd86, %rd40, %rd83;
	ld.global.f32 	%f70, [%rd86];
	add.f32 	%f71, %f70, %f70;
	ld.global.f32 	%f72, [%rd76];
	ld.global.f32 	%f73, [%rd78];
	mul.f32 	%f74, %f73, %f2;
	fma.rn.f32 	%f75, %f72, %f1, %f74;
	ld.global.f32 	%f76, [%rd80];
	fma.rn.f32 	%f77, %f76, %f3, %f75;
	ld.global.f32 	%f78, [%rd84];
	fma.rn.f32 	%f79, %f71, %f77, %f78;
	mul.f32 	%f80, %f14, %f79;
	fma.rn.f32 	%f103, %f80, %f72, %f15;
	fma.rn.f32 	%f104, %f80, %f73, %f16;
	fma.rn.f32 	%f105, %f80, %f76, %f17;
	setp.eq.s32	%p11, %r32, 1;
	@%p11 bra 	BB0_22;

	and.b16  	%rs3, %rs4, 4;
	setp.eq.s16	%p12, %rs3, 0;
	add.s32 	%r22, %r3, -1;
	@%p12 bra 	BB0_17;

	rem.s32 	%r112, %r22, %r32;
	add.s32 	%r113, %r112, %r32;
	rem.s32 	%r166, %r113, %r32;
	bra.uni 	BB0_18;

BB0_17:
	mov.u32 	%r114, 0;
	max.s32 	%r166, %r22, %r114;

BB0_18:
	mad.lo.s32 	%r119, %r166, %r31, %r2;
	mad.lo.s32 	%r124, %r119, %r30, %r1;
	cvt.s64.s32	%rd88, %r124;
	mul.wide.s32 	%rd90, %r124, 4;
	add.s64 	%rd91, %rd11, %rd90;
	add.s64 	%rd93, %rd14, %rd90;
	add.s64 	%rd95, %rd10, %rd90;
	add.s64 	%rd96, %rd17, %rd88;
	ld.global.u8 	%r125, [%rd96];
	shl.b32 	%r126, %r125, 8;
	add.s32 	%r127, %r126, %r5;
	mul.wide.s32 	%rd98, %r127, 4;
	add.s64 	%rd99, %rd37, %rd98;
	add.s64 	%rd101, %rd40, %rd98;
	ld.global.f32 	%f81, [%rd101];
	add.f32 	%f82, %f81, %f81;
	ld.global.f32 	%f83, [%rd91];
	ld.global.f32 	%f84, [%rd93];
	mul.f32 	%f85, %f84, %f2;
	fma.rn.f32 	%f86, %f83, %f1, %f85;
	ld.global.f32 	%f87, [%rd95];
	fma.rn.f32 	%f88, %f87, %f3, %f86;
	ld.global.f32 	%f89, [%rd99];
	fma.rn.f32 	%f90, %f82, %f88, %f89;
	add.f32 	%f21, %f33, %f33;
	mul.f32 	%f91, %f21, %f90;
	fma.rn.f32 	%f22, %f91, %f83, %f103;
	fma.rn.f32 	%f23, %f91, %f84, %f104;
	fma.rn.f32 	%f24, %f91, %f87, %f105;
	add.s32 	%r26, %r3, 1;
	and.b16  	%rs6, %rs3, 255;
	setp.eq.s16	%p13, %rs6, 0;
	@%p13 bra 	BB0_20;

	rem.s32 	%r132, %r26, %r32;
	add.s32 	%r133, %r132, %r32;
	rem.s32 	%r167, %r133, %r32;
	bra.uni 	BB0_21;

BB0_20:
	add.s32 	%r134, %r32, -1;
	min.s32 	%r167, %r26, %r134;

BB0_21:
	mad.lo.s32 	%r139, %r167, %r31, %r2;
	mad.lo.s32 	%r144, %r139, %r30, %r1;
	cvt.s64.s32	%rd103, %r144;
	mul.wide.s32 	%rd105, %r144, 4;
	add.s64 	%rd106, %rd11, %rd105;
	add.s64 	%rd108, %rd14, %rd105;
	add.s64 	%rd110, %rd10, %rd105;
	add.s64 	%rd111, %rd17, %rd103;
	ld.global.u8 	%r145, [%rd111];
	shl.b32 	%r146, %r145, 8;
	add.s32 	%r147, %r146, %r5;
	mul.wide.s32 	%rd113, %r147, 4;
	add.s64 	%rd114, %rd37, %rd113;
	add.s64 	%rd116, %rd40, %rd113;
	ld.global.f32 	%f92, [%rd116];
	add.f32 	%f93, %f92, %f92;
	ld.global.f32 	%f94, [%rd106];
	ld.global.f32 	%f95, [%rd108];
	mul.f32 	%f96, %f95, %f2;
	fma.rn.f32 	%f97, %f94, %f1, %f96;
	ld.global.f32 	%f98, [%rd110];
	fma.rn.f32 	%f99, %f98, %f3, %f97;
	ld.global.f32 	%f100, [%rd114];
	fma.rn.f32 	%f101, %f93, %f99, %f100;
	mul.f32 	%f102, %f21, %f101;
	fma.rn.f32 	%f103, %f102, %f94, %f22;
	fma.rn.f32 	%f104, %f102, %f95, %f23;
	fma.rn.f32 	%f105, %f102, %f98, %f24;

BB0_22:
	mul.wide.s32 	%rd118, %r49, 4;
	add.s64 	%rd119, %rd20, %rd118;
	st.global.f32 	[%rd119], %f103;
	add.s64 	%rd121, %rd23, %rd118;
	st.global.f32 	[%rd121], %f104;
	add.s64 	%rd123, %rd25, %rd118;
	st.global.f32 	[%rd123], %f105;

BB0_23:
	ret;
}


`
	addiecexchange_ptx_35 = `
.version 4.1
.target sm_35
.address_size 64


.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.visible .entry addiecexchange(
	.param .u64 addiecexchange_param_0,
	.param .u64 addiecexchange_param_1,
	.param .u64 addiecexchange_param_2,
	.param .u64 addiecexchange_param_3,
	.param .u64 addiecexchange_param_4,
	.param .u64 addiecexchange_param_5,
	.param .u64 addiecexchange_param_6,
	.param .u64 addiecexchange_param_7,
	.param .u64 addiecexchange_param_8,
	.param .f32 addiecexchange_param_9,
	.param .f32 addiecexchange_param_10,
	.param .f32 addiecexchange_param_11,
	.param .u32 addiecexchange_param_12,
	.param .u32 addiecexchange_param_13,
	.param .u32 addiecexchange_param_14,
	.param .u8 addiecexchange_param_15
)
{
	.reg .pred 	%p<14>;
	.reg .s16 	%rs<14>;
	.reg .s32 	%r<104>;
	.reg .f32 	%f<106>;
	.reg .s64 	%rd<83>;


	ld.param.u64 	%rd11, [addiecexchange_param_0];
	ld.param.u64 	%rd12, [addiecexchange_param_1];
	ld.param.u64 	%rd13, [addiecexchange_param_2];
	ld.param.u64 	%rd14, [addiecexchange_param_3];
	ld.param.u64 	%rd15, [addiecexchange_param_4];
	ld.param.u64 	%rd16, [addiecexchange_param_5];
	ld.param.u64 	%rd17, [addiecexchange_param_6];
	ld.param.u64 	%rd18, [addiecexchange_param_7];
	ld.param.u64 	%rd19, [addiecexchange_param_8];
	ld.param.f32 	%f31, [addiecexchange_param_9];
	ld.param.f32 	%f32, [addiecexchange_param_10];
	ld.param.f32 	%f33, [addiecexchange_param_11];
	ld.param.u32 	%r31, [addiecexchange_param_12];
	ld.param.u32 	%r32, [addiecexchange_param_13];
	ld.param.u32 	%r33, [addiecexchange_param_14];
	ld.param.u8 	%rs4, [addiecexchange_param_15];
	cvta.to.global.u64 	%rd1, %rd18;
	cvta.to.global.u64 	%rd2, %rd17;
	cvta.to.global.u64 	%rd3, %rd19;
	cvta.to.global.u64 	%rd4, %rd16;
	cvta.to.global.u64 	%rd5, %rd15;
	cvta.to.global.u64 	%rd6, %rd14;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %ctaid.x;
	mov.u32 	%r36, %tid.x;
	mad.lo.s32 	%r1, %r34, %r35, %r36;
	mov.u32 	%r37, %ntid.y;
	mov.u32 	%r38, %ctaid.y;
	mov.u32 	%r39, %tid.y;
	mad.lo.s32 	%r2, %r37, %r38, %r39;
	mov.u32 	%r40, %ntid.z;
	mov.u32 	%r41, %ctaid.z;
	mov.u32 	%r42, %tid.z;
	mad.lo.s32 	%r3, %r40, %r41, %r42;
	setp.ge.s32	%p1, %r2, %r32;
	setp.ge.s32	%p2, %r1, %r31;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32	%p4, %r3, %r33;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB5_23;

	mul.lo.s32 	%r4, %r3, %r32;
	add.s32 	%r43, %r4, %r2;
	mul.lo.s32 	%r5, %r43, %r31;
	add.s32 	%r44, %r5, %r1;
	cvt.s64.s32	%rd7, %r44;
	mul.wide.s32 	%rd20, %r44, 4;
	add.s64 	%rd21, %rd6, %rd20;
	add.s64 	%rd22, %rd5, %rd20;
	add.s64 	%rd23, %rd4, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	ld.global.nc.f32 	%f2, [%rd22];
	mul.f32 	%f34, %f2, %f2;
	fma.rn.f32 	%f35, %f1, %f1, %f34;
	ld.global.nc.f32 	%f3, [%rd23];
	fma.rn.f32 	%f36, %f3, %f3, %f35;
	setp.eq.f32	%p6, %f36, 0f00000000;
	@%p6 bra 	BB5_23;

	cvta.to.global.u64 	%rd24, %rd13;
	cvta.to.global.u64 	%rd25, %rd12;
	cvta.to.global.u64 	%rd26, %rd11;
	add.s64 	%rd27, %rd3, %rd7;
	ld.global.nc.u8 	%rs5, [%rd27];
	cvt.u32.u16	%r45, %rs5;
	and.b32  	%r6, %r45, 255;
	shl.b64 	%rd28, %rd7, 2;
	add.s64 	%rd8, %rd26, %rd28;
	ld.global.f32 	%f4, [%rd8];
	add.s64 	%rd9, %rd25, %rd28;
	ld.global.f32 	%f5, [%rd9];
	add.s64 	%rd10, %rd24, %rd28;
	ld.global.f32 	%f6, [%rd10];
	add.s32 	%r7, %r1, -1;
	and.b16  	%rs1, %rs4, 1;
	setp.eq.b16	%p7, %rs1, 1;
	@!%p7 bra 	BB5_4;
	bra.uni 	BB5_3;

BB5_3:
	rem.s32 	%r46, %r7, %r31;
	add.s32 	%r47, %r46, %r31;
	rem.s32 	%r98, %r47, %r31;
	bra.uni 	BB5_5;

BB5_4:
	mov.u32 	%r48, 0;
	max.s32 	%r98, %r7, %r48;

BB5_5:
	add.s32 	%r49, %r98, %r5;
	cvt.s64.s32	%rd29, %r49;
	mul.wide.s32 	%rd30, %r49, 4;
	add.s64 	%rd31, %rd6, %rd30;
	add.s64 	%rd32, %rd5, %rd30;
	add.s64 	%rd33, %rd4, %rd30;
	add.s64 	%rd34, %rd3, %rd29;
	ld.global.nc.u8 	%rs6, [%rd34];
	cvt.u32.u16	%r50, %rs6;
	and.b32  	%r51, %r50, 255;
	shl.b32 	%r52, %r51, 8;
	add.s32 	%r53, %r52, %r6;
	mul.wide.s32 	%rd35, %r53, 4;
	add.s64 	%rd36, %rd2, %rd35;
	add.s64 	%rd37, %rd1, %rd35;
	ld.global.nc.f32 	%f37, [%rd37];
	add.f32 	%f38, %f37, %f37;
	ld.global.nc.f32 	%f39, [%rd31];
	ld.global.nc.f32 	%f40, [%rd32];
	mul.f32 	%f41, %f40, %f2;
	fma.rn.f32 	%f42, %f39, %f1, %f41;
	ld.global.nc.f32 	%f43, [%rd33];
	fma.rn.f32 	%f44, %f43, %f3, %f42;
	ld.global.nc.f32 	%f45, [%rd36];
	fma.rn.f32 	%f46, %f38, %f44, %f45;
	add.f32 	%f7, %f31, %f31;
	mul.f32 	%f47, %f7, %f46;
	fma.rn.f32 	%f8, %f47, %f39, %f4;
	fma.rn.f32 	%f9, %f47, %f40, %f5;
	fma.rn.f32 	%f10, %f47, %f43, %f6;
	add.s32 	%r11, %r1, 1;
	setp.eq.s16	%p8, %rs1, 0;
	@%p8 bra 	BB5_7;

	rem.s32 	%r54, %r11, %r31;
	add.s32 	%r55, %r54, %r31;
	rem.s32 	%r99, %r55, %r31;
	bra.uni 	BB5_8;

BB5_7:
	add.s32 	%r56, %r31, -1;
	min.s32 	%r99, %r11, %r56;

BB5_8:
	add.s32 	%r57, %r99, %r5;
	cvt.s64.s32	%rd38, %r57;
	mul.wide.s32 	%rd39, %r57, 4;
	add.s64 	%rd40, %rd6, %rd39;
	add.s64 	%rd41, %rd5, %rd39;
	add.s64 	%rd42, %rd4, %rd39;
	add.s64 	%rd43, %rd3, %rd38;
	ld.global.nc.u8 	%rs7, [%rd43];
	cvt.u32.u16	%r58, %rs7;
	and.b32  	%r59, %r58, 255;
	shl.b32 	%r60, %r59, 8;
	add.s32 	%r61, %r60, %r6;
	mul.wide.s32 	%rd44, %r61, 4;
	add.s64 	%rd45, %rd2, %rd44;
	add.s64 	%rd46, %rd1, %rd44;
	ld.global.nc.f32 	%f48, [%rd46];
	add.f32 	%f49, %f48, %f48;
	ld.global.nc.f32 	%f50, [%rd40];
	ld.global.nc.f32 	%f51, [%rd41];
	mul.f32 	%f52, %f51, %f2;
	fma.rn.f32 	%f53, %f50, %f1, %f52;
	ld.global.nc.f32 	%f54, [%rd42];
	fma.rn.f32 	%f55, %f54, %f3, %f53;
	ld.global.nc.f32 	%f56, [%rd45];
	fma.rn.f32 	%f57, %f49, %f55, %f56;
	mul.f32 	%f58, %f7, %f57;
	fma.rn.f32 	%f11, %f58, %f50, %f8;
	fma.rn.f32 	%f12, %f58, %f51, %f9;
	fma.rn.f32 	%f13, %f58, %f54, %f10;
	and.b16  	%rs2, %rs4, 2;
	setp.eq.s16	%p9, %rs2, 0;
	add.s32 	%r15, %r2, -1;
	@%p9 bra 	BB5_10;

	rem.s32 	%r62, %r15, %r32;
	add.s32 	%r63, %r62, %r32;
	rem.s32 	%r100, %r63, %r32;
	bra.uni 	BB5_11;

BB5_10:
	mov.u32 	%r64, 0;
	max.s32 	%r100, %r15, %r64;

BB5_11:
	add.s32 	%r65, %r100, %r4;
	mad.lo.s32 	%r66, %r65, %r31, %r1;
	cvt.s64.s32	%rd47, %r66;
	mul.wide.s32 	%rd48, %r66, 4;
	add.s64 	%rd49, %rd6, %rd48;
	add.s64 	%rd50, %rd5, %rd48;
	add.s64 	%rd51, %rd4, %rd48;
	add.s64 	%rd52, %rd3, %rd47;
	ld.global.nc.u8 	%rs8, [%rd52];
	cvt.u32.u16	%r67, %rs8;
	and.b32  	%r68, %r67, 255;
	shl.b32 	%r69, %r68, 8;
	add.s32 	%r70, %r69, %r6;
	mul.wide.s32 	%rd53, %r70, 4;
	add.s64 	%rd54, %rd2, %rd53;
	add.s64 	%rd55, %rd1, %rd53;
	ld.global.nc.f32 	%f59, [%rd55];
	add.f32 	%f60, %f59, %f59;
	ld.global.nc.f32 	%f61, [%rd49];
	ld.global.nc.f32 	%f62, [%rd50];
	mul.f32 	%f63, %f62, %f2;
	fma.rn.f32 	%f64, %f61, %f1, %f63;
	ld.global.nc.f32 	%f65, [%rd51];
	fma.rn.f32 	%f66, %f65, %f3, %f64;
	ld.global.nc.f32 	%f67, [%rd54];
	fma.rn.f32 	%f68, %f60, %f66, %f67;
	add.f32 	%f14, %f32, %f32;
	mul.f32 	%f69, %f14, %f68;
	fma.rn.f32 	%f15, %f69, %f61, %f11;
	fma.rn.f32 	%f16, %f69, %f62, %f12;
	fma.rn.f32 	%f17, %f69, %f65, %f13;
	add.s32 	%r19, %r2, 1;
	and.b16  	%rs9, %rs2, 255;
	setp.eq.s16	%p10, %rs9, 0;
	@%p10 bra 	BB5_13;

	rem.s32 	%r71, %r19, %r32;
	add.s32 	%r72, %r71, %r32;
	rem.s32 	%r101, %r72, %r32;
	bra.uni 	BB5_14;

BB5_13:
	add.s32 	%r73, %r32, -1;
	min.s32 	%r101, %r19, %r73;

BB5_14:
	add.s32 	%r74, %r101, %r4;
	mad.lo.s32 	%r75, %r74, %r31, %r1;
	cvt.s64.s32	%rd56, %r75;
	mul.wide.s32 	%rd57, %r75, 4;
	add.s64 	%rd58, %rd6, %rd57;
	add.s64 	%rd59, %rd5, %rd57;
	add.s64 	%rd60, %rd4, %rd57;
	add.s64 	%rd61, %rd3, %rd56;
	ld.global.nc.u8 	%rs10, [%rd61];
	cvt.u32.u16	%r76, %rs10;
	and.b32  	%r77, %r76, 255;
	shl.b32 	%r78, %r77, 8;
	add.s32 	%r79, %r78, %r6;
	mul.wide.s32 	%rd62, %r79, 4;
	add.s64 	%rd63, %rd2, %rd62;
	add.s64 	%rd64, %rd1, %rd62;
	ld.global.nc.f32 	%f70, [%rd64];
	add.f32 	%f71, %f70, %f70;
	ld.global.nc.f32 	%f72, [%rd58];
	ld.global.nc.f32 	%f73, [%rd59];
	mul.f32 	%f74, %f73, %f2;
	fma.rn.f32 	%f75, %f72, %f1, %f74;
	ld.global.nc.f32 	%f76, [%rd60];
	fma.rn.f32 	%f77, %f76, %f3, %f75;
	ld.global.nc.f32 	%f78, [%rd63];
	fma.rn.f32 	%f79, %f71, %f77, %f78;
	mul.f32 	%f80, %f14, %f79;
	fma.rn.f32 	%f103, %f80, %f72, %f15;
	fma.rn.f32 	%f104, %f80, %f73, %f16;
	fma.rn.f32 	%f105, %f80, %f76, %f17;
	setp.eq.s32	%p11, %r33, 1;
	@%p11 bra 	BB5_22;

	and.b16  	%rs3, %rs4, 4;
	setp.eq.s16	%p12, %rs3, 0;
	add.s32 	%r23, %r3, -1;
	@%p12 bra 	BB5_17;

	rem.s32 	%r80, %r23, %r33;
	add.s32 	%r81, %r80, %r33;
	rem.s32 	%r102, %r81, %r33;
	bra.uni 	BB5_18;

BB5_17:
	mov.u32 	%r82, 0;
	max.s32 	%r102, %r23, %r82;

BB5_18:
	mad.lo.s32 	%r83, %r102, %r32, %r2;
	mad.lo.s32 	%r84, %r83, %r31, %r1;
	cvt.s64.s32	%rd65, %r84;
	mul.wide.s32 	%rd66, %r84, 4;
	add.s64 	%rd67, %rd6, %rd66;
	add.s64 	%rd68, %rd5, %rd66;
	add.s64 	%rd69, %rd4, %rd66;
	add.s64 	%rd70, %rd3, %rd65;
	ld.global.nc.u8 	%rs11, [%rd70];
	cvt.u32.u16	%r85, %rs11;
	and.b32  	%r86, %r85, 255;
	shl.b32 	%r87, %r86, 8;
	add.s32 	%r88, %r87, %r6;
	mul.wide.s32 	%rd71, %r88, 4;
	add.s64 	%rd72, %rd2, %rd71;
	add.s64 	%rd73, %rd1, %rd71;
	ld.global.nc.f32 	%f81, [%rd73];
	add.f32 	%f82, %f81, %f81;
	ld.global.nc.f32 	%f83, [%rd67];
	ld.global.nc.f32 	%f84, [%rd68];
	mul.f32 	%f85, %f84, %f2;
	fma.rn.f32 	%f86, %f83, %f1, %f85;
	ld.global.nc.f32 	%f87, [%rd69];
	fma.rn.f32 	%f88, %f87, %f3, %f86;
	ld.global.nc.f32 	%f89, [%rd72];
	fma.rn.f32 	%f90, %f82, %f88, %f89;
	add.f32 	%f21, %f33, %f33;
	mul.f32 	%f91, %f21, %f90;
	fma.rn.f32 	%f22, %f91, %f83, %f103;
	fma.rn.f32 	%f23, %f91, %f84, %f104;
	fma.rn.f32 	%f24, %f91, %f87, %f105;
	add.s32 	%r27, %r3, 1;
	and.b16  	%rs12, %rs3, 255;
	setp.eq.s16	%p13, %rs12, 0;
	@%p13 bra 	BB5_20;

	rem.s32 	%r89, %r27, %r33;
	add.s32 	%r90, %r89, %r33;
	rem.s32 	%r103, %r90, %r33;
	bra.uni 	BB5_21;

BB5_20:
	add.s32 	%r91, %r33, -1;
	min.s32 	%r103, %r27, %r91;

BB5_21:
	mad.lo.s32 	%r92, %r103, %r32, %r2;
	mad.lo.s32 	%r93, %r92, %r31, %r1;
	cvt.s64.s32	%rd74, %r93;
	mul.wide.s32 	%rd75, %r93, 4;
	add.s64 	%rd76, %rd6, %rd75;
	add.s64 	%rd77, %rd5, %rd75;
	add.s64 	%rd78, %rd4, %rd75;
	add.s64 	%rd79, %rd3, %rd74;
	ld.global.nc.u8 	%rs13, [%rd79];
	cvt.u32.u16	%r94, %rs13;
	and.b32  	%r95, %r94, 255;
	shl.b32 	%r96, %r95, 8;
	add.s32 	%r97, %r96, %r6;
	mul.wide.s32 	%rd80, %r97, 4;
	add.s64 	%rd81, %rd2, %rd80;
	add.s64 	%rd82, %rd1, %rd80;
	ld.global.nc.f32 	%f92, [%rd82];
	add.f32 	%f93, %f92, %f92;
	ld.global.nc.f32 	%f94, [%rd76];
	ld.global.nc.f32 	%f95, [%rd77];
	mul.f32 	%f96, %f95, %f2;
	fma.rn.f32 	%f97, %f94, %f1, %f96;
	ld.global.nc.f32 	%f98, [%rd78];
	fma.rn.f32 	%f99, %f98, %f3, %f97;
	ld.global.nc.f32 	%f100, [%rd81];
	fma.rn.f32 	%f101, %f93, %f99, %f100;
	mul.f32 	%f102, %f21, %f101;
	fma.rn.f32 	%f103, %f102, %f94, %f22;
	fma.rn.f32 	%f104, %f102, %f95, %f23;
	fma.rn.f32 	%f105, %f102, %f98, %f24;

BB5_22:
	st.global.f32 	[%rd8], %f103;
	st.global.f32 	[%rd9], %f104;
	st.global.f32 	[%rd10], %f105;

BB5_23:
	ret;
}


`
	addiecexchange_ptx_50 = `
.version 4.1
.target sm_50
.address_size 64


.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.visible .entry addiecexchange(
	.param .u64 addiecexchange_param_0,
	.param .u64 addiecexchange_param_1,
	.param .u64 addiecexchange_param_2,
	.param .u64 addiecexchange_param_3,
	.param .u64 addiecexchange_param_4,
	.param .u64 addiecexchange_param_5,
	.param .u64 addiecexchange_param_6,
	.param .u64 addiecexchange_param_7,
	.param .u64 addiecexchange_param_8,
	.param .f32 addiecexchange_param_9,
	.param .f32 addiecexchange_param_10,
	.param .f32 addiecexchange_param_11,
	.param .u32 addiecexchange_param_12,
	.param .u32 addiecexchange_param_13,
	.param .u32 addiecexchange_param_14,
	.param .u8 addiecexchange_param_15
)
{
	.reg .pred 	%p<14>;
	.reg .s16 	%rs<14>;
	.reg .s32 	%r<104>;
	.reg .f32 	%f<106>;
	.reg .s64 	%rd<83>;


	ld.param.u64 	%rd11, [addiecexchange_param_0];
	ld.param.u64 	%rd12, [addiecexchange_param_1];
	ld.param.u64 	%rd13, [addiecexchange_param_2];
	ld.param.u64 	%rd14, [addiecexchange_param_3];
	ld.param.u64 	%rd15, [addiecexchange_param_4];
	ld.param.u64 	%rd16, [addiecexchange_param_5];
	ld.param.u64 	%rd17, [addiecexchange_param_6];
	ld.param.u64 	%rd18, [addiecexchange_param_7];
	ld.param.u64 	%rd19, [addiecexchange_param_8];
	ld.param.f32 	%f31, [addiecexchange_param_9];
	ld.param.f32 	%f32, [addiecexchange_param_10];
	ld.param.f32 	%f33, [addiecexchange_param_11];
	ld.param.u32 	%r31, [addiecexchange_param_12];
	ld.param.u32 	%r32, [addiecexchange_param_13];
	ld.param.u32 	%r33, [addiecexchange_param_14];
	ld.param.u8 	%rs4, [addiecexchange_param_15];
	cvta.to.global.u64 	%rd1, %rd18;
	cvta.to.global.u64 	%rd2, %rd17;
	cvta.to.global.u64 	%rd3, %rd19;
	cvta.to.global.u64 	%rd4, %rd16;
	cvta.to.global.u64 	%rd5, %rd15;
	cvta.to.global.u64 	%rd6, %rd14;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %ctaid.x;
	mov.u32 	%r36, %tid.x;
	mad.lo.s32 	%r1, %r34, %r35, %r36;
	mov.u32 	%r37, %ntid.y;
	mov.u32 	%r38, %ctaid.y;
	mov.u32 	%r39, %tid.y;
	mad.lo.s32 	%r2, %r37, %r38, %r39;
	mov.u32 	%r40, %ntid.z;
	mov.u32 	%r41, %ctaid.z;
	mov.u32 	%r42, %tid.z;
	mad.lo.s32 	%r3, %r40, %r41, %r42;
	setp.ge.s32	%p1, %r2, %r32;
	setp.ge.s32	%p2, %r1, %r31;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32	%p4, %r3, %r33;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB5_23;

	mul.lo.s32 	%r4, %r3, %r32;
	add.s32 	%r43, %r4, %r2;
	mul.lo.s32 	%r5, %r43, %r31;
	add.s32 	%r44, %r5, %r1;
	cvt.s64.s32	%rd7, %r44;
	mul.wide.s32 	%rd20, %r44, 4;
	add.s64 	%rd21, %rd6, %rd20;
	add.s64 	%rd22, %rd5, %rd20;
	add.s64 	%rd23, %rd4, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	ld.global.nc.f32 	%f2, [%rd22];
	mul.f32 	%f34, %f2, %f2;
	fma.rn.f32 	%f35, %f1, %f1, %f34;
	ld.global.nc.f32 	%f3, [%rd23];
	fma.rn.f32 	%f36, %f3, %f3, %f35;
	setp.eq.f32	%p6, %f36, 0f00000000;
	@%p6 bra 	BB5_23;

	cvta.to.global.u64 	%rd24, %rd13;
	cvta.to.global.u64 	%rd25, %rd12;
	cvta.to.global.u64 	%rd26, %rd11;
	add.s64 	%rd27, %rd3, %rd7;
	ld.global.nc.u8 	%rs5, [%rd27];
	cvt.u32.u16	%r45, %rs5;
	and.b32  	%r6, %r45, 255;
	shl.b64 	%rd28, %rd7, 2;
	add.s64 	%rd8, %rd26, %rd28;
	ld.global.f32 	%f4, [%rd8];
	add.s64 	%rd9, %rd25, %rd28;
	ld.global.f32 	%f5, [%rd9];
	add.s64 	%rd10, %rd24, %rd28;
	ld.global.f32 	%f6, [%rd10];
	add.s32 	%r7, %r1, -1;
	and.b16  	%rs1, %rs4, 1;
	setp.eq.b16	%p7, %rs1, 1;
	@!%p7 bra 	BB5_4;
	bra.uni 	BB5_3;

BB5_3:
	rem.s32 	%r46, %r7, %r31;
	add.s32 	%r47, %r46, %r31;
	rem.s32 	%r98, %r47, %r31;
	bra.uni 	BB5_5;

BB5_4:
	mov.u32 	%r48, 0;
	max.s32 	%r98, %r7, %r48;

BB5_5:
	add.s32 	%r49, %r98, %r5;
	cvt.s64.s32	%rd29, %r49;
	mul.wide.s32 	%rd30, %r49, 4;
	add.s64 	%rd31, %rd6, %rd30;
	add.s64 	%rd32, %rd5, %rd30;
	add.s64 	%rd33, %rd4, %rd30;
	add.s64 	%rd34, %rd3, %rd29;
	ld.global.nc.u8 	%rs6, [%rd34];
	cvt.u32.u16	%r50, %rs6;
	and.b32  	%r51, %r50, 255;
	shl.b32 	%r52, %r51, 8;
	add.s32 	%r53, %r52, %r6;
	mul.wide.s32 	%rd35, %r53, 4;
	add.s64 	%rd36, %rd2, %rd35;
	add.s64 	%rd37, %rd1, %rd35;
	ld.global.nc.f32 	%f37, [%rd37];
	add.f32 	%f38, %f37, %f37;
	ld.global.nc.f32 	%f39, [%rd31];
	ld.global.nc.f32 	%f40, [%rd32];
	mul.f32 	%f41, %f40, %f2;
	fma.rn.f32 	%f42, %f39, %f1, %f41;
	ld.global.nc.f32 	%f43, [%rd33];
	fma.rn.f32 	%f44, %f43, %f3, %f42;
	ld.global.nc.f32 	%f45, [%rd36];
	fma.rn.f32 	%f46, %f38, %f44, %f45;
	add.f32 	%f7, %f31, %f31;
	mul.f32 	%f47, %f7, %f46;
	fma.rn.f32 	%f8, %f47, %f39, %f4;
	fma.rn.f32 	%f9, %f47, %f40, %f5;
	fma.rn.f32 	%f10, %f47, %f43, %f6;
	add.s32 	%r11, %r1, 1;
	setp.eq.s16	%p8, %rs1, 0;
	@%p8 bra 	BB5_7;

	rem.s32 	%r54, %r11, %r31;
	add.s32 	%r55, %r54, %r31;
	rem.s32 	%r99, %r55, %r31;
	bra.uni 	BB5_8;

BB5_7:
	add.s32 	%r56, %r31, -1;
	min.s32 	%r99, %r11, %r56;

BB5_8:
	add.s32 	%r57, %r99, %r5;
	cvt.s64.s32	%rd38, %r57;
	mul.wide.s32 	%rd39, %r57, 4;
	add.s64 	%rd40, %rd6, %rd39;
	add.s64 	%rd41, %rd5, %rd39;
	add.s64 	%rd42, %rd4, %rd39;
	add.s64 	%rd43, %rd3, %rd38;
	ld.global.nc.u8 	%rs7, [%rd43];
	cvt.u32.u16	%r58, %rs7;
	and.b32  	%r59, %r58, 255;
	shl.b32 	%r60, %r59, 8;
	add.s32 	%r61, %r60, %r6;
	mul.wide.s32 	%rd44, %r61, 4;
	add.s64 	%rd45, %rd2, %rd44;
	add.s64 	%rd46, %rd1, %rd44;
	ld.global.nc.f32 	%f48, [%rd46];
	add.f32 	%f49, %f48, %f48;
	ld.global.nc.f32 	%f50, [%rd40];
	ld.global.nc.f32 	%f51, [%rd41];
	mul.f32 	%f52, %f51, %f2;
	fma.rn.f32 	%f53, %f50, %f1, %f52;
	ld.global.nc.f32 	%f54, [%rd42];
	fma.rn.f32 	%f55, %f54, %f3, %f53;
	ld.global.nc.f32 	%f56, [%rd45];
	fma.rn.f32 	%f57, %f49, %f55, %f56;
	mul.f32 	%f58, %f7, %f57;
	fma.rn.f32 	%f11, %f58, %f50, %f8;
	fma.rn.f32 	%f12, %f58, %f51, %f9;
	fma.rn.f32 	%f13, %f58, %f54, %f10;
	and.b16  	%rs2, %rs4, 2;
	setp.eq.s16	%p9, %rs2, 0;
	add.s32 	%r15, %r2, -1;
	@%p9 bra 	BB5_10;

	rem.s32 	%r62, %r15, %r32;
	add.s32 	%r63, %r62, %r32;
	rem.s32 	%r100, %r63, %r32;
	bra.uni 	BB5_11;

BB5_10:
	mov.u32 	%r64, 0;
	max.s32 	%r100, %r15, %r64;

BB5_11:
	add.s32 	%r65, %r100, %r4;
	mad.lo.s32 	%r66, %r65, %r31, %r1;
	cvt.s64.s32	%rd47, %r66;
	mul.wide.s32 	%rd48, %r66, 4;
	add.s64 	%rd49, %rd6, %rd48;
	add.s64 	%rd50, %rd5, %rd48;
	add.s64 	%rd51, %rd4, %rd48;
	add.s64 	%rd52, %rd3, %rd47;
	ld.global.nc.u8 	%rs8, [%rd52];
	cvt.u32.u16	%r67, %rs8;
	and.b32  	%r68, %r67, 255;
	shl.b32 	%r69, %r68, 8;
	add.s32 	%r70, %r69, %r6;
	mul.wide.s32 	%rd53, %r70, 4;
	add.s64 	%rd54, %rd2, %rd53;
	add.s64 	%rd55, %rd1, %rd53;
	ld.global.nc.f32 	%f59, [%rd55];
	add.f32 	%f60, %f59, %f59;
	ld.global.nc.f32 	%f61, [%rd49];
	ld.global.nc.f32 	%f62, [%rd50];
	mul.f32 	%f63, %f62, %f2;
	fma.rn.f32 	%f64, %f61, %f1, %f63;
	ld.global.nc.f32 	%f65, [%rd51];
	fma.rn.f32 	%f66, %f65, %f3, %f64;
	ld.global.nc.f32 	%f67, [%rd54];
	fma.rn.f32 	%f68, %f60, %f66, %f67;
	add.f32 	%f14, %f32, %f32;
	mul.f32 	%f69, %f14, %f68;
	fma.rn.f32 	%f15, %f69, %f61, %f11;
	fma.rn.f32 	%f16, %f69, %f62, %f12;
	fma.rn.f32 	%f17, %f69, %f65, %f13;
	add.s32 	%r19, %r2, 1;
	and.b16  	%rs9, %rs2, 255;
	setp.eq.s16	%p10, %rs9, 0;
	@%p10 bra 	BB5_13;

	rem.s32 	%r71, %r19, %r32;
	add.s32 	%r72, %r71, %r32;
	rem.s32 	%r101, %r72, %r32;
	bra.uni 	BB5_14;

BB5_13:
	add.s32 	%r73, %r32, -1;
	min.s32 	%r101, %r19, %r73;

BB5_14:
	add.s32 	%r74, %r101, %r4;
	mad.lo.s32 	%r75, %r74, %r31, %r1;
	cvt.s64.s32	%rd56, %r75;
	mul.wide.s32 	%rd57, %r75, 4;
	add.s64 	%rd58, %rd6, %rd57;
	add.s64 	%rd59, %rd5, %rd57;
	add.s64 	%rd60, %rd4, %rd57;
	add.s64 	%rd61, %rd3, %rd56;
	ld.global.nc.u8 	%rs10, [%rd61];
	cvt.u32.u16	%r76, %rs10;
	and.b32  	%r77, %r76, 255;
	shl.b32 	%r78, %r77, 8;
	add.s32 	%r79, %r78, %r6;
	mul.wide.s32 	%rd62, %r79, 4;
	add.s64 	%rd63, %rd2, %rd62;
	add.s64 	%rd64, %rd1, %rd62;
	ld.global.nc.f32 	%f70, [%rd64];
	add.f32 	%f71, %f70, %f70;
	ld.global.nc.f32 	%f72, [%rd58];
	ld.global.nc.f32 	%f73, [%rd59];
	mul.f32 	%f74, %f73, %f2;
	fma.rn.f32 	%f75, %f72, %f1, %f74;
	ld.global.nc.f32 	%f76, [%rd60];
	fma.rn.f32 	%f77, %f76, %f3, %f75;
	ld.global.nc.f32 	%f78, [%rd63];
	fma.rn.f32 	%f79, %f71, %f77, %f78;
	mul.f32 	%f80, %f14, %f79;
	fma.rn.f32 	%f103, %f80, %f72, %f15;
	fma.rn.f32 	%f104, %f80, %f73, %f16;
	fma.rn.f32 	%f105, %f80, %f76, %f17;
	setp.eq.s32	%p11, %r33, 1;
	@%p11 bra 	BB5_22;

	and.b16  	%rs3, %rs4, 4;
	setp.eq.s16	%p12, %rs3, 0;
	add.s32 	%r23, %r3, -1;
	@%p12 bra 	BB5_17;

	rem.s32 	%r80, %r23, %r33;
	add.s32 	%r81, %r80, %r33;
	rem.s32 	%r102, %r81, %r33;
	bra.uni 	BB5_18;

BB5_17:
	mov.u32 	%r82, 0;
	max.s32 	%r102, %r23, %r82;

BB5_18:
	mad.lo.s32 	%r83, %r102, %r32, %r2;
	mad.lo.s32 	%r84, %r83, %r31, %r1;
	cvt.s64.s32	%rd65, %r84;
	mul.wide.s32 	%rd66, %r84, 4;
	add.s64 	%rd67, %rd6, %rd66;
	add.s64 	%rd68, %rd5, %rd66;
	add.s64 	%rd69, %rd4, %rd66;
	add.s64 	%rd70, %rd3, %rd65;
	ld.global.nc.u8 	%rs11, [%rd70];
	cvt.u32.u16	%r85, %rs11;
	and.b32  	%r86, %r85, 255;
	shl.b32 	%r87, %r86, 8;
	add.s32 	%r88, %r87, %r6;
	mul.wide.s32 	%rd71, %r88, 4;
	add.s64 	%rd72, %rd2, %rd71;
	add.s64 	%rd73, %rd1, %rd71;
	ld.global.nc.f32 	%f81, [%rd73];
	add.f32 	%f82, %f81, %f81;
	ld.global.nc.f32 	%f83, [%rd67];
	ld.global.nc.f32 	%f84, [%rd68];
	mul.f32 	%f85, %f84, %f2;
	fma.rn.f32 	%f86, %f83, %f1, %f85;
	ld.global.nc.f32 	%f87, [%rd69];
	fma.rn.f32 	%f88, %f87, %f3, %f86;
	ld.global.nc.f32 	%f89, [%rd72];
	fma.rn.f32 	%f90, %f82, %f88, %f89;
	add.f32 	%f21, %f33, %f33;
	mul.f32 	%f91, %f21, %f90;
	fma.rn.f32 	%f22, %f91, %f83, %f103;
	fma.rn.f32 	%f23, %f91, %f84, %f104;
	fma.rn.f32 	%f24, %f91, %f87, %f105;
	add.s32 	%r27, %r3, 1;
	and.b16  	%rs12, %rs3, 255;
	setp.eq.s16	%p13, %rs12, 0;
	@%p13 bra 	BB5_20;

	rem.s32 	%r89, %r27, %r33;
	add.s32 	%r90, %r89, %r33;
	rem.s32 	%r103, %r90, %r33;
	bra.uni 	BB5_21;

BB5_20:
	add.s32 	%r91, %r33, -1;
	min.s32 	%r103, %r27, %r91;

BB5_21:
	mad.lo.s32 	%r92, %r103, %r32, %r2;
	mad.lo.s32 	%r93, %r92, %r31, %r1;
	cvt.s64.s32	%rd74, %r93;
	mul.wide.s32 	%rd75, %r93, 4;
	add.s64 	%rd76, %rd6, %rd75;
	add.s64 	%rd77, %rd5, %rd75;
	add.s64 	%rd78, %rd4, %rd75;
	add.s64 	%rd79, %rd3, %rd74;
	ld.global.nc.u8 	%rs13, [%rd79];
	cvt.u32.u16	%r94, %rs13;
	and.b32  	%r95, %r94, 255;
	shl.b32 	%r96, %r95, 8;
	add.s32 	%r97, %r96, %r6;
	mul.wide.s32 	%rd80, %r97, 4;
	add.s64 	%rd81, %rd2, %rd80;
	add.s64 	%rd82, %rd1, %rd80;
	ld.global.nc.f32 	%f92, [%rd82];
	add.f32 	%f93, %f92, %f92;
	ld.global.nc.f32 	%f94, [%rd76];
	ld.global.nc.f32 	%f95, [%rd77];
	mul.f32 	%f96, %f95, %f2;
	fma.rn.f32 	%f97, %f94, %f1, %f96;
	ld.global.nc.f32 	%f98, [%rd78];
	fma.rn.f32 	%f99, %f98, %f3, %f97;
	ld.global.nc.f32 	%f100, [%rd81];
	fma.rn.f32 	%f101, %f93, %f99, %f100;
	mul.f32 	%f102, %f21, %f101;
	fma.rn.f32 	%f103, %f102, %f94, %f22;
	fma.rn.f32 	%f104, %f102, %f95, %f23;
	fma.rn.f32 	%f105, %f102, %f98, %f24;

BB5_22:
	st.global.f32 	[%rd8], %f103;
	st.global.f32 	[%rd9], %f104;
	st.global.f32 	[%rd10], %f105;

BB5_23:
	ret;
}


`
)
