package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for addiecexchange kernel
var addiecexchange_code cu.Function

// Stores the arguments for addiecexchange kernel invocation
type addiecexchange_args_t struct {
	arg_Bx      unsafe.Pointer
	arg_By      unsafe.Pointer
	arg_Bz      unsafe.Pointer
	arg_mx      unsafe.Pointer
	arg_my      unsafe.Pointer
	arg_mz      unsafe.Pointer
	arg_j1LUT2d unsafe.Pointer
	arg_j2LUT2d unsafe.Pointer
	arg_regions unsafe.Pointer
	arg_wx      float32
	arg_wy      float32
	arg_wz      float32
	arg_Nx      int
	arg_Ny      int
	arg_Nz      int
	arg_PBC     byte
	argptr      [16]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for addiecexchange kernel invocation
var addiecexchange_args addiecexchange_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	addiecexchange_args.argptr[0] = unsafe.Pointer(&addiecexchange_args.arg_Bx)
	addiecexchange_args.argptr[1] = unsafe.Pointer(&addiecexchange_args.arg_By)
	addiecexchange_args.argptr[2] = unsafe.Pointer(&addiecexchange_args.arg_Bz)
	addiecexchange_args.argptr[3] = unsafe.Pointer(&addiecexchange_args.arg_mx)
	addiecexchange_args.argptr[4] = unsafe.Pointer(&addiecexchange_args.arg_my)
	addiecexchange_args.argptr[5] = unsafe.Pointer(&addiecexchange_args.arg_mz)
	addiecexchange_args.argptr[6] = unsafe.Pointer(&addiecexchange_args.arg_j1LUT2d)
	addiecexchange_args.argptr[7] = unsafe.Pointer(&addiecexchange_args.arg_j2LUT2d)
	addiecexchange_args.argptr[8] = unsafe.Pointer(&addiecexchange_args.arg_regions)
	addiecexchange_args.argptr[9] = unsafe.Pointer(&addiecexchange_args.arg_wx)
	addiecexchange_args.argptr[10] = unsafe.Pointer(&addiecexchange_args.arg_wy)
	addiecexchange_args.argptr[11] = unsafe.Pointer(&addiecexchange_args.arg_wz)
	addiecexchange_args.argptr[12] = unsafe.Pointer(&addiecexchange_args.arg_Nx)
	addiecexchange_args.argptr[13] = unsafe.Pointer(&addiecexchange_args.arg_Ny)
	addiecexchange_args.argptr[14] = unsafe.Pointer(&addiecexchange_args.arg_Nz)
	addiecexchange_args.argptr[15] = unsafe.Pointer(&addiecexchange_args.arg_PBC)
}

// Wrapper for addiecexchange CUDA kernel, asynchronous.
func k_addiecexchange_async(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, j1LUT2d unsafe.Pointer, j2LUT2d unsafe.Pointer, regions unsafe.Pointer, wx float32, wy float32, wz float32, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("addiecexchange")
	}

	addiecexchange_args.Lock()
	defer addiecexchange_args.Unlock()

	if addiecexchange_code == 0 {
		addiecexchange_code = fatbinLoad(addiecexchange_map, "addiecexchange")
	}

	addiecexchange_args.arg_Bx = Bx
	addiecexchange_args.arg_By = By
	addiecexchange_args.arg_Bz = Bz
	addiecexchange_args.arg_mx = mx
	addiecexchange_args.arg_my = my
	addiecexchange_args.arg_mz = mz
	addiecexchange_args.arg_j1LUT2d = j1LUT2d
	addiecexchange_args.arg_j2LUT2d = j2LUT2d
	addiecexchange_args.arg_regions = regions
	addiecexchange_args.arg_wx = wx
	addiecexchange_args.arg_wy = wy
	addiecexchange_args.arg_wz = wz
	addiecexchange_args.arg_Nx = Nx
	addiecexchange_args.arg_Ny = Ny
	addiecexchange_args.arg_Nz = Nz
	addiecexchange_args.arg_PBC = PBC

	args := addiecexchange_args.argptr[:]
	cu.LaunchKernel(addiecexchange_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("addiecexchange")
	}
}

// maps compute capability on PTX code for addiecexchange kernel.
var addiecexchange_map = map[int]string{0: "",
	20: addiecexchange_ptx_20,
	30: addiecexchange_ptx_30,
	35: addiecexchange_ptx_35,
	50: addiecexchange_ptx_50}

// addiecexchange PTX code for various compute capabilities.
const (
	addiecexchange_ptx_20 = `
.version 4.1
.target sm_20
.address_size 64


.visible .entry addiecexchange(
	.param .u64 addiecexchange_param_0,
	.param .u64 addiecexchange_param_1,
	.param .u64 addiecexchange_param_2,
	.param .u64 addiecexchange_param_3,
	.param .u64 addiecexchange_param_4,
	.param .u64 addiecexchange_param_5,
	.param .u64 addiecexchange_param_6,
	.param .u64 addiecexchange_param_7,
	.param .u64 addiecexchange_param_8,
	.param .f32 addiecexchange_param_9,
	.param .f32 addiecexchange_param_10,
	.param .f32 addiecexchange_param_11,
	.param .u32 addiecexchange_param_12,
	.param .u32 addiecexchange_param_13,
	.param .u32 addiecexchange_param_14,
	.param .u8 addiecexchange_param_15
)
{
	.reg .pred 	%p<14>;
	.reg .s16 	%rs<8>;
	.reg .s32 	%r<177>;
	.reg .f32 	%f<103>;
	.reg .s64 	%rd<122>;


	ld.param.u64 	%rd2, [addiecexchange_param_0];
	ld.param.u64 	%rd3, [addiecexchange_param_1];
	ld.param.u64 	%rd4, [addiecexchange_param_2];
	ld.param.u64 	%rd5, [addiecexchange_param_3];
	ld.param.u64 	%rd6, [addiecexchange_param_4];
	ld.param.u64 	%rd7, [addiecexchange_param_5];
	ld.param.u64 	%rd8, [addiecexchange_param_6];
	ld.param.u64 	%rd9, [addiecexchange_param_7];
	ld.param.u64 	%rd10, [addiecexchange_param_8];
	ld.param.f32 	%f28, [addiecexchange_param_9];
	ld.param.f32 	%f29, [addiecexchange_param_10];
	ld.param.f32 	%f30, [addiecexchange_param_11];
	ld.param.u32 	%r29, [addiecexchange_param_12];
	ld.param.u32 	%r30, [addiecexchange_param_13];
	ld.param.u32 	%r31, [addiecexchange_param_14];
	ld.param.u8 	%rs3, [addiecexchange_param_15];
	mov.u32 	%r32, %ntid.x;
	mov.u32 	%r33, %ctaid.x;
	mov.u32 	%r34, %tid.x;
	mad.lo.s32 	%r1, %r32, %r33, %r34;
	mov.u32 	%r35, %ntid.y;
	mov.u32 	%r36, %ctaid.y;
	mov.u32 	%r37, %tid.y;
	mad.lo.s32 	%r2, %r35, %r36, %r37;
	mov.u32 	%r38, %ntid.z;
	mov.u32 	%r39, %ctaid.z;
	mov.u32 	%r40, %tid.z;
	mad.lo.s32 	%r3, %r38, %r39, %r40;
	setp.ge.s32	%p1, %r2, %r30;
	setp.ge.s32	%p2, %r1, %r29;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32	%p4, %r3, %r31;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_23;

	cvta.to.global.u64 	%rd11, %rd7;
	mad.lo.s32 	%r41, %r3, %r30, %r2;
	mul.lo.s32 	%r4, %r41, %r29;
	add.s32 	%r42, %r4, %r1;
	cvta.to.global.u64 	%rd12, %rd5;
	mul.wide.s32 	%rd13, %r42, 4;
	add.s64 	%rd14, %rd12, %rd13;
	cvta.to.global.u64 	%rd15, %rd6;
	add.s64 	%rd16, %rd15, %rd13;
	add.s64 	%rd17, %rd11, %rd13;
	ld.global.f32 	%f1, [%rd14];
	ld.global.f32 	%f2, [%rd16];
	mul.f32 	%f31, %f2, %f2;
	fma.rn.f32 	%f32, %f1, %f1, %f31;
	ld.global.f32 	%f3, [%rd17];
	fma.rn.f32 	%f33, %f3, %f3, %f32;
	setp.eq.f32	%p6, %f33, 0f00000000;
	@%p6 bra 	BB0_23;

	cvta.to.global.u64 	%rd18, %rd10;
	mad.lo.s32 	%r48, %r41, %r29, %r1;
	cvt.s64.s32	%rd19, %r48;
	add.s64 	%rd20, %rd18, %rd19;
	ld.global.u8 	%r5, [%rd20];
	cvta.to.global.u64 	%rd21, %rd2;
	mul.wide.s32 	%rd22, %r48, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.f32 	%f4, [%rd23];
	cvta.to.global.u64 	%rd24, %rd3;
	add.s64 	%rd25, %rd24, %rd22;
	ld.global.f32 	%f5, [%rd25];
	cvta.to.global.u64 	%rd26, %rd4;
	add.s64 	%rd1, %rd26, %rd22;
	ld.global.f32 	%f6, [%rd1];
	and.b16  	%rs4, %rs3, 1;
	setp.eq.b16	%p7, %rs4, 1;
	@!%p7 bra 	BB0_4;
	bra.uni 	BB0_3;

BB0_3:
	add.s32 	%r53, %r1, -1;
	rem.s32 	%r54, %r53, %r29;
	add.s32 	%r55, %r54, %r29;
	rem.s32 	%r171, %r55, %r29;
	bra.uni 	BB0_5;

BB0_4:
	add.s32 	%r60, %r1, -1;
	mov.u32 	%r61, 0;
	max.s32 	%r171, %r60, %r61;

BB0_5:
	add.s32 	%r62, %r171, %r4;
	cvt.s64.s32	%rd28, %r62;
	mul.wide.s32 	%rd30, %r62, 4;
	add.s64 	%rd31, %rd12, %rd30;
	add.s64 	%rd33, %rd15, %rd30;
	add.s64 	%rd35, %rd11, %rd30;
	add.s64 	%rd36, %rd18, %rd28;
	ld.global.u8 	%r63, [%rd36];
	shl.b32 	%r64, %r63, 8;
	add.s32 	%r65, %r64, %r5;
	cvta.to.global.u64 	%rd37, %rd8;
	mul.wide.s32 	%rd38, %r65, 4;
	add.s64 	%rd39, %rd37, %rd38;
	cvta.to.global.u64 	%rd40, %rd9;
	add.s64 	%rd41, %rd40, %rd38;
	ld.global.f32 	%f34, [%rd41];
	add.f32 	%f35, %f34, %f34;
	ld.global.f32 	%f36, [%rd31];
	ld.global.f32 	%f37, [%rd33];
	mul.f32 	%f38, %f37, %f2;
	fma.rn.f32 	%f39, %f36, %f1, %f38;
	ld.global.f32 	%f40, [%rd35];
	fma.rn.f32 	%f41, %f40, %f3, %f39;
	ld.global.f32 	%f42, [%rd39];
	fma.rn.f32 	%f43, %f35, %f41, %f42;
	mul.f32 	%f44, %f43, %f28;
	fma.rn.f32 	%f7, %f44, %f36, %f4;
	fma.rn.f32 	%f8, %f44, %f37, %f5;
	fma.rn.f32 	%f9, %f44, %f40, %f6;
	add.s32 	%r9, %r1, 1;
	@!%p7 bra 	BB0_7;
	bra.uni 	BB0_6;

BB0_6:
	rem.s32 	%r70, %r9, %r29;
	add.s32 	%r71, %r70, %r29;
	rem.s32 	%r172, %r71, %r29;
	bra.uni 	BB0_8;

BB0_7:
	add.s32 	%r72, %r29, -1;
	min.s32 	%r172, %r9, %r72;

BB0_8:
	add.s32 	%r73, %r172, %r4;
	cvt.s64.s32	%rd43, %r73;
	mul.wide.s32 	%rd45, %r73, 4;
	add.s64 	%rd46, %rd12, %rd45;
	add.s64 	%rd48, %rd15, %rd45;
	add.s64 	%rd50, %rd11, %rd45;
	add.s64 	%rd51, %rd18, %rd43;
	ld.global.u8 	%r74, [%rd51];
	shl.b32 	%r75, %r74, 8;
	add.s32 	%r76, %r75, %r5;
	mul.wide.s32 	%rd53, %r76, 4;
	add.s64 	%rd54, %rd37, %rd53;
	add.s64 	%rd56, %rd40, %rd53;
	ld.global.f32 	%f45, [%rd56];
	add.f32 	%f46, %f45, %f45;
	ld.global.f32 	%f47, [%rd46];
	ld.global.f32 	%f48, [%rd48];
	mul.f32 	%f49, %f48, %f2;
	fma.rn.f32 	%f50, %f47, %f1, %f49;
	ld.global.f32 	%f51, [%rd50];
	fma.rn.f32 	%f52, %f51, %f3, %f50;
	ld.global.f32 	%f53, [%rd54];
	fma.rn.f32 	%f54, %f46, %f52, %f53;
	mul.f32 	%f55, %f54, %f28;
	fma.rn.f32 	%f10, %f55, %f47, %f7;
	fma.rn.f32 	%f11, %f55, %f48, %f8;
	fma.rn.f32 	%f12, %f55, %f51, %f9;
	and.b16  	%rs1, %rs3, 2;
	setp.eq.s16	%p9, %rs1, 0;
	add.s32 	%r13, %r2, -1;
	@%p9 bra 	BB0_10;

	rem.s32 	%r81, %r13, %r30;
	add.s32 	%r82, %r81, %r30;
	rem.s32 	%r173, %r82, %r30;
	bra.uni 	BB0_11;

BB0_10:
	mov.u32 	%r83, 0;
	max.s32 	%r173, %r13, %r83;

BB0_11:
	mad.lo.s32 	%r88, %r3, %r30, %r173;
	mad.lo.s32 	%r93, %r88, %r29, %r1;
	cvt.s64.s32	%rd58, %r93;
	mul.wide.s32 	%rd60, %r93, 4;
	add.s64 	%rd61, %rd12, %rd60;
	add.s64 	%rd63, %rd15, %rd60;
	add.s64 	%rd65, %rd11, %rd60;
	add.s64 	%rd66, %rd18, %rd58;
	ld.global.u8 	%r94, [%rd66];
	shl.b32 	%r95, %r94, 8;
	add.s32 	%r96, %r95, %r5;
	mul.wide.s32 	%rd68, %r96, 4;
	add.s64 	%rd69, %rd37, %rd68;
	add.s64 	%rd71, %rd40, %rd68;
	ld.global.f32 	%f56, [%rd71];
	add.f32 	%f57, %f56, %f56;
	ld.global.f32 	%f58, [%rd61];
	ld.global.f32 	%f59, [%rd63];
	mul.f32 	%f60, %f59, %f2;
	fma.rn.f32 	%f61, %f58, %f1, %f60;
	ld.global.f32 	%f62, [%rd65];
	fma.rn.f32 	%f63, %f62, %f3, %f61;
	ld.global.f32 	%f64, [%rd69];
	fma.rn.f32 	%f65, %f57, %f63, %f64;
	mul.f32 	%f66, %f65, %f29;
	fma.rn.f32 	%f13, %f66, %f58, %f10;
	fma.rn.f32 	%f14, %f66, %f59, %f11;
	fma.rn.f32 	%f15, %f66, %f62, %f12;
	add.s32 	%r17, %r2, 1;
	and.b16  	%rs6, %rs1, 255;
	setp.eq.s16	%p10, %rs6, 0;
	@%p10 bra 	BB0_13;

	rem.s32 	%r101, %r17, %r30;
	add.s32 	%r102, %r101, %r30;
	rem.s32 	%r174, %r102, %r30;
	bra.uni 	BB0_14;

BB0_13:
	add.s32 	%r103, %r30, -1;
	min.s32 	%r174, %r17, %r103;

BB0_14:
	mad.lo.s32 	%r108, %r3, %r30, %r174;
	mad.lo.s32 	%r113, %r108, %r29, %r1;
	cvt.s64.s32	%rd73, %r113;
	mul.wide.s32 	%rd75, %r113, 4;
	add.s64 	%rd76, %rd12, %rd75;
	add.s64 	%rd78, %rd15, %rd75;
	add.s64 	%rd80, %rd11, %rd75;
	add.s64 	%rd81, %rd18, %rd73;
	ld.global.u8 	%r114, [%rd81];
	shl.b32 	%r115, %r114, 8;
	add.s32 	%r116, %r115, %r5;
	mul.wide.s32 	%rd83, %r116, 4;
	add.s64 	%rd84, %rd37, %rd83;
	add.s64 	%rd86, %rd40, %rd83;
	ld.global.f32 	%f67, [%rd86];
	add.f32 	%f68, %f67, %f67;
	ld.global.f32 	%f69, [%rd76];
	ld.global.f32 	%f70, [%rd78];
	mul.f32 	%f71, %f70, %f2;
	fma.rn.f32 	%f72, %f69, %f1, %f71;
	ld.global.f32 	%f73, [%rd80];
	fma.rn.f32 	%f74, %f73, %f3, %f72;
	ld.global.f32 	%f75, [%rd84];
	fma.rn.f32 	%f76, %f68, %f74, %f75;
	mul.f32 	%f77, %f76, %f29;
	fma.rn.f32 	%f100, %f77, %f69, %f13;
	fma.rn.f32 	%f101, %f77, %f70, %f14;
	fma.rn.f32 	%f102, %f77, %f73, %f15;
	setp.eq.s32	%p11, %r31, 1;
	@%p11 bra 	BB0_22;

	and.b16  	%rs2, %rs3, 4;
	setp.eq.s16	%p12, %rs2, 0;
	add.s32 	%r21, %r3, -1;
	@%p12 bra 	BB0_17;

	rem.s32 	%r121, %r21, %r31;
	add.s32 	%r122, %r121, %r31;
	rem.s32 	%r175, %r122, %r31;
	bra.uni 	BB0_18;

BB0_17:
	mov.u32 	%r123, 0;
	max.s32 	%r175, %r21, %r123;

BB0_18:
	mad.lo.s32 	%r128, %r175, %r30, %r2;
	mad.lo.s32 	%r133, %r128, %r29, %r1;
	cvt.s64.s32	%rd88, %r133;
	mul.wide.s32 	%rd90, %r133, 4;
	add.s64 	%rd91, %rd12, %rd90;
	add.s64 	%rd93, %rd15, %rd90;
	add.s64 	%rd95, %rd11, %rd90;
	add.s64 	%rd96, %rd18, %rd88;
	ld.global.u8 	%r134, [%rd96];
	shl.b32 	%r135, %r134, 8;
	add.s32 	%r136, %r135, %r5;
	mul.wide.s32 	%rd98, %r136, 4;
	add.s64 	%rd99, %rd37, %rd98;
	add.s64 	%rd101, %rd40, %rd98;
	ld.global.f32 	%f78, [%rd101];
	add.f32 	%f79, %f78, %f78;
	ld.global.f32 	%f80, [%rd91];
	ld.global.f32 	%f81, [%rd93];
	mul.f32 	%f82, %f81, %f2;
	fma.rn.f32 	%f83, %f80, %f1, %f82;
	ld.global.f32 	%f84, [%rd95];
	fma.rn.f32 	%f85, %f84, %f3, %f83;
	ld.global.f32 	%f86, [%rd99];
	fma.rn.f32 	%f87, %f79, %f85, %f86;
	mul.f32 	%f88, %f87, %f30;
	fma.rn.f32 	%f19, %f88, %f80, %f100;
	fma.rn.f32 	%f20, %f88, %f81, %f101;
	fma.rn.f32 	%f21, %f88, %f84, %f102;
	add.s32 	%r25, %r3, 1;
	and.b16  	%rs7, %rs2, 255;
	setp.eq.s16	%p13, %rs7, 0;
	@%p13 bra 	BB0_20;

	rem.s32 	%r141, %r25, %r31;
	add.s32 	%r142, %r141, %r31;
	rem.s32 	%r176, %r142, %r31;
	bra.uni 	BB0_21;

BB0_20:
	add.s32 	%r143, %r31, -1;
	min.s32 	%r176, %r25, %r143;

BB0_21:
	mad.lo.s32 	%r148, %r176, %r30, %r2;
	mad.lo.s32 	%r153, %r148, %r29, %r1;
	cvt.s64.s32	%rd103, %r153;
	mul.wide.s32 	%rd105, %r153, 4;
	add.s64 	%rd106, %rd12, %rd105;
	add.s64 	%rd108, %rd15, %rd105;
	add.s64 	%rd110, %rd11, %rd105;
	add.s64 	%rd111, %rd18, %rd103;
	ld.global.u8 	%r154, [%rd111];
	shl.b32 	%r155, %r154, 8;
	add.s32 	%r156, %r155, %r5;
	mul.wide.s32 	%rd113, %r156, 4;
	add.s64 	%rd114, %rd37, %rd113;
	add.s64 	%rd116, %rd40, %rd113;
	ld.global.f32 	%f89, [%rd116];
	add.f32 	%f90, %f89, %f89;
	ld.global.f32 	%f91, [%rd106];
	ld.global.f32 	%f92, [%rd108];
	mul.f32 	%f93, %f92, %f2;
	fma.rn.f32 	%f94, %f91, %f1, %f93;
	ld.global.f32 	%f95, [%rd110];
	fma.rn.f32 	%f96, %f95, %f3, %f94;
	ld.global.f32 	%f97, [%rd114];
	fma.rn.f32 	%f98, %f90, %f96, %f97;
	mul.f32 	%f99, %f98, %f30;
	fma.rn.f32 	%f100, %f99, %f91, %f19;
	fma.rn.f32 	%f101, %f99, %f92, %f20;
	fma.rn.f32 	%f102, %f99, %f95, %f21;

BB0_22:
	mul.wide.s32 	%rd118, %r48, 4;
	add.s64 	%rd119, %rd21, %rd118;
	st.global.f32 	[%rd119], %f100;
	add.s64 	%rd121, %rd24, %rd118;
	st.global.f32 	[%rd121], %f101;
	st.global.f32 	[%rd1], %f102;

BB0_23:
	ret;
}


`
	addiecexchange_ptx_30 = `
.version 4.1
.target sm_30
.address_size 64


.visible .entry addiecexchange(
	.param .u64 addiecexchange_param_0,
	.param .u64 addiecexchange_param_1,
	.param .u64 addiecexchange_param_2,
	.param .u64 addiecexchange_param_3,
	.param .u64 addiecexchange_param_4,
	.param .u64 addiecexchange_param_5,
	.param .u64 addiecexchange_param_6,
	.param .u64 addiecexchange_param_7,
	.param .u64 addiecexchange_param_8,
	.param .f32 addiecexchange_param_9,
	.param .f32 addiecexchange_param_10,
	.param .f32 addiecexchange_param_11,
	.param .u32 addiecexchange_param_12,
	.param .u32 addiecexchange_param_13,
	.param .u32 addiecexchange_param_14,
	.param .u8 addiecexchange_param_15
)
{
	.reg .pred 	%p<14>;
	.reg .s16 	%rs<8>;
	.reg .s32 	%r<177>;
	.reg .f32 	%f<103>;
	.reg .s64 	%rd<122>;


	ld.param.u64 	%rd2, [addiecexchange_param_0];
	ld.param.u64 	%rd3, [addiecexchange_param_1];
	ld.param.u64 	%rd4, [addiecexchange_param_2];
	ld.param.u64 	%rd5, [addiecexchange_param_3];
	ld.param.u64 	%rd6, [addiecexchange_param_4];
	ld.param.u64 	%rd7, [addiecexchange_param_5];
	ld.param.u64 	%rd8, [addiecexchange_param_6];
	ld.param.u64 	%rd9, [addiecexchange_param_7];
	ld.param.u64 	%rd10, [addiecexchange_param_8];
	ld.param.f32 	%f28, [addiecexchange_param_9];
	ld.param.f32 	%f29, [addiecexchange_param_10];
	ld.param.f32 	%f30, [addiecexchange_param_11];
	ld.param.u32 	%r29, [addiecexchange_param_12];
	ld.param.u32 	%r30, [addiecexchange_param_13];
	ld.param.u32 	%r31, [addiecexchange_param_14];
	ld.param.u8 	%rs3, [addiecexchange_param_15];
	mov.u32 	%r32, %ntid.x;
	mov.u32 	%r33, %ctaid.x;
	mov.u32 	%r34, %tid.x;
	mad.lo.s32 	%r1, %r32, %r33, %r34;
	mov.u32 	%r35, %ntid.y;
	mov.u32 	%r36, %ctaid.y;
	mov.u32 	%r37, %tid.y;
	mad.lo.s32 	%r2, %r35, %r36, %r37;
	mov.u32 	%r38, %ntid.z;
	mov.u32 	%r39, %ctaid.z;
	mov.u32 	%r40, %tid.z;
	mad.lo.s32 	%r3, %r38, %r39, %r40;
	setp.ge.s32	%p1, %r2, %r30;
	setp.ge.s32	%p2, %r1, %r29;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32	%p4, %r3, %r31;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_23;

	cvta.to.global.u64 	%rd11, %rd7;
	mad.lo.s32 	%r41, %r3, %r30, %r2;
	mul.lo.s32 	%r4, %r41, %r29;
	add.s32 	%r42, %r4, %r1;
	cvta.to.global.u64 	%rd12, %rd5;
	mul.wide.s32 	%rd13, %r42, 4;
	add.s64 	%rd14, %rd12, %rd13;
	cvta.to.global.u64 	%rd15, %rd6;
	add.s64 	%rd16, %rd15, %rd13;
	add.s64 	%rd17, %rd11, %rd13;
	ld.global.f32 	%f1, [%rd14];
	ld.global.f32 	%f2, [%rd16];
	mul.f32 	%f31, %f2, %f2;
	fma.rn.f32 	%f32, %f1, %f1, %f31;
	ld.global.f32 	%f3, [%rd17];
	fma.rn.f32 	%f33, %f3, %f3, %f32;
	setp.eq.f32	%p6, %f33, 0f00000000;
	@%p6 bra 	BB0_23;

	cvta.to.global.u64 	%rd18, %rd10;
	mad.lo.s32 	%r48, %r41, %r29, %r1;
	cvt.s64.s32	%rd19, %r48;
	add.s64 	%rd20, %rd18, %rd19;
	ld.global.u8 	%r5, [%rd20];
	cvta.to.global.u64 	%rd21, %rd2;
	mul.wide.s32 	%rd22, %r48, 4;
	add.s64 	%rd23, %rd21, %rd22;
	ld.global.f32 	%f4, [%rd23];
	cvta.to.global.u64 	%rd24, %rd3;
	add.s64 	%rd25, %rd24, %rd22;
	ld.global.f32 	%f5, [%rd25];
	cvta.to.global.u64 	%rd26, %rd4;
	add.s64 	%rd1, %rd26, %rd22;
	ld.global.f32 	%f6, [%rd1];
	and.b16  	%rs4, %rs3, 1;
	setp.eq.b16	%p7, %rs4, 1;
	@!%p7 bra 	BB0_4;
	bra.uni 	BB0_3;

BB0_3:
	add.s32 	%r53, %r1, -1;
	rem.s32 	%r54, %r53, %r29;
	add.s32 	%r55, %r54, %r29;
	rem.s32 	%r171, %r55, %r29;
	bra.uni 	BB0_5;

BB0_4:
	add.s32 	%r60, %r1, -1;
	mov.u32 	%r61, 0;
	max.s32 	%r171, %r60, %r61;

BB0_5:
	add.s32 	%r62, %r171, %r4;
	cvt.s64.s32	%rd28, %r62;
	mul.wide.s32 	%rd30, %r62, 4;
	add.s64 	%rd31, %rd12, %rd30;
	add.s64 	%rd33, %rd15, %rd30;
	add.s64 	%rd35, %rd11, %rd30;
	add.s64 	%rd36, %rd18, %rd28;
	ld.global.u8 	%r63, [%rd36];
	shl.b32 	%r64, %r63, 8;
	add.s32 	%r65, %r64, %r5;
	cvta.to.global.u64 	%rd37, %rd8;
	mul.wide.s32 	%rd38, %r65, 4;
	add.s64 	%rd39, %rd37, %rd38;
	cvta.to.global.u64 	%rd40, %rd9;
	add.s64 	%rd41, %rd40, %rd38;
	ld.global.f32 	%f34, [%rd41];
	add.f32 	%f35, %f34, %f34;
	ld.global.f32 	%f36, [%rd31];
	ld.global.f32 	%f37, [%rd33];
	mul.f32 	%f38, %f37, %f2;
	fma.rn.f32 	%f39, %f36, %f1, %f38;
	ld.global.f32 	%f40, [%rd35];
	fma.rn.f32 	%f41, %f40, %f3, %f39;
	ld.global.f32 	%f42, [%rd39];
	fma.rn.f32 	%f43, %f35, %f41, %f42;
	mul.f32 	%f44, %f43, %f28;
	fma.rn.f32 	%f7, %f44, %f36, %f4;
	fma.rn.f32 	%f8, %f44, %f37, %f5;
	fma.rn.f32 	%f9, %f44, %f40, %f6;
	add.s32 	%r9, %r1, 1;
	@!%p7 bra 	BB0_7;
	bra.uni 	BB0_6;

BB0_6:
	rem.s32 	%r70, %r9, %r29;
	add.s32 	%r71, %r70, %r29;
	rem.s32 	%r172, %r71, %r29;
	bra.uni 	BB0_8;

BB0_7:
	add.s32 	%r72, %r29, -1;
	min.s32 	%r172, %r9, %r72;

BB0_8:
	add.s32 	%r73, %r172, %r4;
	cvt.s64.s32	%rd43, %r73;
	mul.wide.s32 	%rd45, %r73, 4;
	add.s64 	%rd46, %rd12, %rd45;
	add.s64 	%rd48, %rd15, %rd45;
	add.s64 	%rd50, %rd11, %rd45;
	add.s64 	%rd51, %rd18, %rd43;
	ld.global.u8 	%r74, [%rd51];
	shl.b32 	%r75, %r74, 8;
	add.s32 	%r76, %r75, %r5;
	mul.wide.s32 	%rd53, %r76, 4;
	add.s64 	%rd54, %rd37, %rd53;
	add.s64 	%rd56, %rd40, %rd53;
	ld.global.f32 	%f45, [%rd56];
	add.f32 	%f46, %f45, %f45;
	ld.global.f32 	%f47, [%rd46];
	ld.global.f32 	%f48, [%rd48];
	mul.f32 	%f49, %f48, %f2;
	fma.rn.f32 	%f50, %f47, %f1, %f49;
	ld.global.f32 	%f51, [%rd50];
	fma.rn.f32 	%f52, %f51, %f3, %f50;
	ld.global.f32 	%f53, [%rd54];
	fma.rn.f32 	%f54, %f46, %f52, %f53;
	mul.f32 	%f55, %f54, %f28;
	fma.rn.f32 	%f10, %f55, %f47, %f7;
	fma.rn.f32 	%f11, %f55, %f48, %f8;
	fma.rn.f32 	%f12, %f55, %f51, %f9;
	and.b16  	%rs1, %rs3, 2;
	setp.eq.s16	%p9, %rs1, 0;
	add.s32 	%r13, %r2, -1;
	@%p9 bra 	BB0_10;

	rem.s32 	%r81, %r13, %r30;
	add.s32 	%r82, %r81, %r30;
	rem.s32 	%r173, %r82, %r30;
	bra.uni 	BB0_11;

BB0_10:
	mov.u32 	%r83, 0;
	max.s32 	%r173, %r13, %r83;

BB0_11:
	mad.lo.s32 	%r88, %r3, %r30, %r173;
	mad.lo.s32 	%r93, %r88, %r29, %r1;
	cvt.s64.s32	%rd58, %r93;
	mul.wide.s32 	%rd60, %r93, 4;
	add.s64 	%rd61, %rd12, %rd60;
	add.s64 	%rd63, %rd15, %rd60;
	add.s64 	%rd65, %rd11, %rd60;
	add.s64 	%rd66, %rd18, %rd58;
	ld.global.u8 	%r94, [%rd66];
	shl.b32 	%r95, %r94, 8;
	add.s32 	%r96, %r95, %r5;
	mul.wide.s32 	%rd68, %r96, 4;
	add.s64 	%rd69, %rd37, %rd68;
	add.s64 	%rd71, %rd40, %rd68;
	ld.global.f32 	%f56, [%rd71];
	add.f32 	%f57, %f56, %f56;
	ld.global.f32 	%f58, [%rd61];
	ld.global.f32 	%f59, [%rd63];
	mul.f32 	%f60, %f59, %f2;
	fma.rn.f32 	%f61, %f58, %f1, %f60;
	ld.global.f32 	%f62, [%rd65];
	fma.rn.f32 	%f63, %f62, %f3, %f61;
	ld.global.f32 	%f64, [%rd69];
	fma.rn.f32 	%f65, %f57, %f63, %f64;
	mul.f32 	%f66, %f65, %f29;
	fma.rn.f32 	%f13, %f66, %f58, %f10;
	fma.rn.f32 	%f14, %f66, %f59, %f11;
	fma.rn.f32 	%f15, %f66, %f62, %f12;
	add.s32 	%r17, %r2, 1;
	and.b16  	%rs6, %rs1, 255;
	setp.eq.s16	%p10, %rs6, 0;
	@%p10 bra 	BB0_13;

	rem.s32 	%r101, %r17, %r30;
	add.s32 	%r102, %r101, %r30;
	rem.s32 	%r174, %r102, %r30;
	bra.uni 	BB0_14;

BB0_13:
	add.s32 	%r103, %r30, -1;
	min.s32 	%r174, %r17, %r103;

BB0_14:
	mad.lo.s32 	%r108, %r3, %r30, %r174;
	mad.lo.s32 	%r113, %r108, %r29, %r1;
	cvt.s64.s32	%rd73, %r113;
	mul.wide.s32 	%rd75, %r113, 4;
	add.s64 	%rd76, %rd12, %rd75;
	add.s64 	%rd78, %rd15, %rd75;
	add.s64 	%rd80, %rd11, %rd75;
	add.s64 	%rd81, %rd18, %rd73;
	ld.global.u8 	%r114, [%rd81];
	shl.b32 	%r115, %r114, 8;
	add.s32 	%r116, %r115, %r5;
	mul.wide.s32 	%rd83, %r116, 4;
	add.s64 	%rd84, %rd37, %rd83;
	add.s64 	%rd86, %rd40, %rd83;
	ld.global.f32 	%f67, [%rd86];
	add.f32 	%f68, %f67, %f67;
	ld.global.f32 	%f69, [%rd76];
	ld.global.f32 	%f70, [%rd78];
	mul.f32 	%f71, %f70, %f2;
	fma.rn.f32 	%f72, %f69, %f1, %f71;
	ld.global.f32 	%f73, [%rd80];
	fma.rn.f32 	%f74, %f73, %f3, %f72;
	ld.global.f32 	%f75, [%rd84];
	fma.rn.f32 	%f76, %f68, %f74, %f75;
	mul.f32 	%f77, %f76, %f29;
	fma.rn.f32 	%f100, %f77, %f69, %f13;
	fma.rn.f32 	%f101, %f77, %f70, %f14;
	fma.rn.f32 	%f102, %f77, %f73, %f15;
	setp.eq.s32	%p11, %r31, 1;
	@%p11 bra 	BB0_22;

	and.b16  	%rs2, %rs3, 4;
	setp.eq.s16	%p12, %rs2, 0;
	add.s32 	%r21, %r3, -1;
	@%p12 bra 	BB0_17;

	rem.s32 	%r121, %r21, %r31;
	add.s32 	%r122, %r121, %r31;
	rem.s32 	%r175, %r122, %r31;
	bra.uni 	BB0_18;

BB0_17:
	mov.u32 	%r123, 0;
	max.s32 	%r175, %r21, %r123;

BB0_18:
	mad.lo.s32 	%r128, %r175, %r30, %r2;
	mad.lo.s32 	%r133, %r128, %r29, %r1;
	cvt.s64.s32	%rd88, %r133;
	mul.wide.s32 	%rd90, %r133, 4;
	add.s64 	%rd91, %rd12, %rd90;
	add.s64 	%rd93, %rd15, %rd90;
	add.s64 	%rd95, %rd11, %rd90;
	add.s64 	%rd96, %rd18, %rd88;
	ld.global.u8 	%r134, [%rd96];
	shl.b32 	%r135, %r134, 8;
	add.s32 	%r136, %r135, %r5;
	mul.wide.s32 	%rd98, %r136, 4;
	add.s64 	%rd99, %rd37, %rd98;
	add.s64 	%rd101, %rd40, %rd98;
	ld.global.f32 	%f78, [%rd101];
	add.f32 	%f79, %f78, %f78;
	ld.global.f32 	%f80, [%rd91];
	ld.global.f32 	%f81, [%rd93];
	mul.f32 	%f82, %f81, %f2;
	fma.rn.f32 	%f83, %f80, %f1, %f82;
	ld.global.f32 	%f84, [%rd95];
	fma.rn.f32 	%f85, %f84, %f3, %f83;
	ld.global.f32 	%f86, [%rd99];
	fma.rn.f32 	%f87, %f79, %f85, %f86;
	mul.f32 	%f88, %f87, %f30;
	fma.rn.f32 	%f19, %f88, %f80, %f100;
	fma.rn.f32 	%f20, %f88, %f81, %f101;
	fma.rn.f32 	%f21, %f88, %f84, %f102;
	add.s32 	%r25, %r3, 1;
	and.b16  	%rs7, %rs2, 255;
	setp.eq.s16	%p13, %rs7, 0;
	@%p13 bra 	BB0_20;

	rem.s32 	%r141, %r25, %r31;
	add.s32 	%r142, %r141, %r31;
	rem.s32 	%r176, %r142, %r31;
	bra.uni 	BB0_21;

BB0_20:
	add.s32 	%r143, %r31, -1;
	min.s32 	%r176, %r25, %r143;

BB0_21:
	mad.lo.s32 	%r148, %r176, %r30, %r2;
	mad.lo.s32 	%r153, %r148, %r29, %r1;
	cvt.s64.s32	%rd103, %r153;
	mul.wide.s32 	%rd105, %r153, 4;
	add.s64 	%rd106, %rd12, %rd105;
	add.s64 	%rd108, %rd15, %rd105;
	add.s64 	%rd110, %rd11, %rd105;
	add.s64 	%rd111, %rd18, %rd103;
	ld.global.u8 	%r154, [%rd111];
	shl.b32 	%r155, %r154, 8;
	add.s32 	%r156, %r155, %r5;
	mul.wide.s32 	%rd113, %r156, 4;
	add.s64 	%rd114, %rd37, %rd113;
	add.s64 	%rd116, %rd40, %rd113;
	ld.global.f32 	%f89, [%rd116];
	add.f32 	%f90, %f89, %f89;
	ld.global.f32 	%f91, [%rd106];
	ld.global.f32 	%f92, [%rd108];
	mul.f32 	%f93, %f92, %f2;
	fma.rn.f32 	%f94, %f91, %f1, %f93;
	ld.global.f32 	%f95, [%rd110];
	fma.rn.f32 	%f96, %f95, %f3, %f94;
	ld.global.f32 	%f97, [%rd114];
	fma.rn.f32 	%f98, %f90, %f96, %f97;
	mul.f32 	%f99, %f98, %f30;
	fma.rn.f32 	%f100, %f99, %f91, %f19;
	fma.rn.f32 	%f101, %f99, %f92, %f20;
	fma.rn.f32 	%f102, %f99, %f95, %f21;

BB0_22:
	mul.wide.s32 	%rd118, %r48, 4;
	add.s64 	%rd119, %rd21, %rd118;
	st.global.f32 	[%rd119], %f100;
	add.s64 	%rd121, %rd24, %rd118;
	st.global.f32 	[%rd121], %f101;
	st.global.f32 	[%rd1], %f102;

BB0_23:
	ret;
}


`
	addiecexchange_ptx_35 = `
.version 4.1
.target sm_35
.address_size 64


.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.visible .entry addiecexchange(
	.param .u64 addiecexchange_param_0,
	.param .u64 addiecexchange_param_1,
	.param .u64 addiecexchange_param_2,
	.param .u64 addiecexchange_param_3,
	.param .u64 addiecexchange_param_4,
	.param .u64 addiecexchange_param_5,
	.param .u64 addiecexchange_param_6,
	.param .u64 addiecexchange_param_7,
	.param .u64 addiecexchange_param_8,
	.param .f32 addiecexchange_param_9,
	.param .f32 addiecexchange_param_10,
	.param .f32 addiecexchange_param_11,
	.param .u32 addiecexchange_param_12,
	.param .u32 addiecexchange_param_13,
	.param .u32 addiecexchange_param_14,
	.param .u8 addiecexchange_param_15
)
{
	.reg .pred 	%p<14>;
	.reg .s16 	%rs<14>;
	.reg .s32 	%r<104>;
	.reg .f32 	%f<103>;
	.reg .s64 	%rd<83>;


	ld.param.u64 	%rd11, [addiecexchange_param_0];
	ld.param.u64 	%rd12, [addiecexchange_param_1];
	ld.param.u64 	%rd13, [addiecexchange_param_2];
	ld.param.u64 	%rd14, [addiecexchange_param_3];
	ld.param.u64 	%rd15, [addiecexchange_param_4];
	ld.param.u64 	%rd16, [addiecexchange_param_5];
	ld.param.u64 	%rd17, [addiecexchange_param_6];
	ld.param.u64 	%rd18, [addiecexchange_param_7];
	ld.param.u64 	%rd19, [addiecexchange_param_8];
	ld.param.f32 	%f28, [addiecexchange_param_9];
	ld.param.f32 	%f29, [addiecexchange_param_10];
	ld.param.f32 	%f30, [addiecexchange_param_11];
	ld.param.u32 	%r31, [addiecexchange_param_12];
	ld.param.u32 	%r32, [addiecexchange_param_13];
	ld.param.u32 	%r33, [addiecexchange_param_14];
	ld.param.u8 	%rs4, [addiecexchange_param_15];
	cvta.to.global.u64 	%rd1, %rd18;
	cvta.to.global.u64 	%rd2, %rd17;
	cvta.to.global.u64 	%rd3, %rd19;
	cvta.to.global.u64 	%rd4, %rd16;
	cvta.to.global.u64 	%rd5, %rd15;
	cvta.to.global.u64 	%rd6, %rd14;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %ctaid.x;
	mov.u32 	%r36, %tid.x;
	mad.lo.s32 	%r1, %r34, %r35, %r36;
	mov.u32 	%r37, %ntid.y;
	mov.u32 	%r38, %ctaid.y;
	mov.u32 	%r39, %tid.y;
	mad.lo.s32 	%r2, %r37, %r38, %r39;
	mov.u32 	%r40, %ntid.z;
	mov.u32 	%r41, %ctaid.z;
	mov.u32 	%r42, %tid.z;
	mad.lo.s32 	%r3, %r40, %r41, %r42;
	setp.ge.s32	%p1, %r2, %r32;
	setp.ge.s32	%p2, %r1, %r31;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32	%p4, %r3, %r33;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB5_23;

	mul.lo.s32 	%r4, %r3, %r32;
	add.s32 	%r43, %r4, %r2;
	mul.lo.s32 	%r5, %r43, %r31;
	add.s32 	%r44, %r5, %r1;
	cvt.s64.s32	%rd7, %r44;
	mul.wide.s32 	%rd20, %r44, 4;
	add.s64 	%rd21, %rd6, %rd20;
	add.s64 	%rd22, %rd5, %rd20;
	add.s64 	%rd23, %rd4, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	ld.global.nc.f32 	%f2, [%rd22];
	mul.f32 	%f31, %f2, %f2;
	fma.rn.f32 	%f32, %f1, %f1, %f31;
	ld.global.nc.f32 	%f3, [%rd23];
	fma.rn.f32 	%f33, %f3, %f3, %f32;
	setp.eq.f32	%p6, %f33, 0f00000000;
	@%p6 bra 	BB5_23;

	cvta.to.global.u64 	%rd24, %rd13;
	cvta.to.global.u64 	%rd25, %rd12;
	cvta.to.global.u64 	%rd26, %rd11;
	add.s64 	%rd27, %rd3, %rd7;
	ld.global.nc.u8 	%rs5, [%rd27];
	cvt.u32.u16	%r45, %rs5;
	and.b32  	%r6, %r45, 255;
	shl.b64 	%rd28, %rd7, 2;
	add.s64 	%rd8, %rd26, %rd28;
	ld.global.f32 	%f4, [%rd8];
	add.s64 	%rd9, %rd25, %rd28;
	ld.global.f32 	%f5, [%rd9];
	add.s64 	%rd10, %rd24, %rd28;
	ld.global.f32 	%f6, [%rd10];
	add.s32 	%r7, %r1, -1;
	and.b16  	%rs1, %rs4, 1;
	setp.eq.b16	%p7, %rs1, 1;
	@!%p7 bra 	BB5_4;
	bra.uni 	BB5_3;

BB5_3:
	rem.s32 	%r46, %r7, %r31;
	add.s32 	%r47, %r46, %r31;
	rem.s32 	%r98, %r47, %r31;
	bra.uni 	BB5_5;

BB5_4:
	mov.u32 	%r48, 0;
	max.s32 	%r98, %r7, %r48;

BB5_5:
	add.s32 	%r49, %r98, %r5;
	cvt.s64.s32	%rd29, %r49;
	mul.wide.s32 	%rd30, %r49, 4;
	add.s64 	%rd31, %rd6, %rd30;
	add.s64 	%rd32, %rd5, %rd30;
	add.s64 	%rd33, %rd4, %rd30;
	add.s64 	%rd34, %rd3, %rd29;
	ld.global.nc.u8 	%rs6, [%rd34];
	cvt.u32.u16	%r50, %rs6;
	and.b32  	%r51, %r50, 255;
	shl.b32 	%r52, %r51, 8;
	add.s32 	%r53, %r52, %r6;
	mul.wide.s32 	%rd35, %r53, 4;
	add.s64 	%rd36, %rd2, %rd35;
	add.s64 	%rd37, %rd1, %rd35;
	ld.global.nc.f32 	%f34, [%rd37];
	add.f32 	%f35, %f34, %f34;
	ld.global.nc.f32 	%f36, [%rd31];
	ld.global.nc.f32 	%f37, [%rd32];
	mul.f32 	%f38, %f37, %f2;
	fma.rn.f32 	%f39, %f36, %f1, %f38;
	ld.global.nc.f32 	%f40, [%rd33];
	fma.rn.f32 	%f41, %f40, %f3, %f39;
	ld.global.nc.f32 	%f42, [%rd36];
	fma.rn.f32 	%f43, %f35, %f41, %f42;
	mul.f32 	%f44, %f43, %f28;
	fma.rn.f32 	%f7, %f44, %f36, %f4;
	fma.rn.f32 	%f8, %f44, %f37, %f5;
	fma.rn.f32 	%f9, %f44, %f40, %f6;
	add.s32 	%r11, %r1, 1;
	setp.eq.s16	%p8, %rs1, 0;
	@%p8 bra 	BB5_7;

	rem.s32 	%r54, %r11, %r31;
	add.s32 	%r55, %r54, %r31;
	rem.s32 	%r99, %r55, %r31;
	bra.uni 	BB5_8;

BB5_7:
	add.s32 	%r56, %r31, -1;
	min.s32 	%r99, %r11, %r56;

BB5_8:
	add.s32 	%r57, %r99, %r5;
	cvt.s64.s32	%rd38, %r57;
	mul.wide.s32 	%rd39, %r57, 4;
	add.s64 	%rd40, %rd6, %rd39;
	add.s64 	%rd41, %rd5, %rd39;
	add.s64 	%rd42, %rd4, %rd39;
	add.s64 	%rd43, %rd3, %rd38;
	ld.global.nc.u8 	%rs7, [%rd43];
	cvt.u32.u16	%r58, %rs7;
	and.b32  	%r59, %r58, 255;
	shl.b32 	%r60, %r59, 8;
	add.s32 	%r61, %r60, %r6;
	mul.wide.s32 	%rd44, %r61, 4;
	add.s64 	%rd45, %rd2, %rd44;
	add.s64 	%rd46, %rd1, %rd44;
	ld.global.nc.f32 	%f45, [%rd46];
	add.f32 	%f46, %f45, %f45;
	ld.global.nc.f32 	%f47, [%rd40];
	ld.global.nc.f32 	%f48, [%rd41];
	mul.f32 	%f49, %f48, %f2;
	fma.rn.f32 	%f50, %f47, %f1, %f49;
	ld.global.nc.f32 	%f51, [%rd42];
	fma.rn.f32 	%f52, %f51, %f3, %f50;
	ld.global.nc.f32 	%f53, [%rd45];
	fma.rn.f32 	%f54, %f46, %f52, %f53;
	mul.f32 	%f55, %f54, %f28;
	fma.rn.f32 	%f10, %f55, %f47, %f7;
	fma.rn.f32 	%f11, %f55, %f48, %f8;
	fma.rn.f32 	%f12, %f55, %f51, %f9;
	and.b16  	%rs2, %rs4, 2;
	setp.eq.s16	%p9, %rs2, 0;
	add.s32 	%r15, %r2, -1;
	@%p9 bra 	BB5_10;

	rem.s32 	%r62, %r15, %r32;
	add.s32 	%r63, %r62, %r32;
	rem.s32 	%r100, %r63, %r32;
	bra.uni 	BB5_11;

BB5_10:
	mov.u32 	%r64, 0;
	max.s32 	%r100, %r15, %r64;

BB5_11:
	add.s32 	%r65, %r100, %r4;
	mad.lo.s32 	%r66, %r65, %r31, %r1;
	cvt.s64.s32	%rd47, %r66;
	mul.wide.s32 	%rd48, %r66, 4;
	add.s64 	%rd49, %rd6, %rd48;
	add.s64 	%rd50, %rd5, %rd48;
	add.s64 	%rd51, %rd4, %rd48;
	add.s64 	%rd52, %rd3, %rd47;
	ld.global.nc.u8 	%rs8, [%rd52];
	cvt.u32.u16	%r67, %rs8;
	and.b32  	%r68, %r67, 255;
	shl.b32 	%r69, %r68, 8;
	add.s32 	%r70, %r69, %r6;
	mul.wide.s32 	%rd53, %r70, 4;
	add.s64 	%rd54, %rd2, %rd53;
	add.s64 	%rd55, %rd1, %rd53;
	ld.global.nc.f32 	%f56, [%rd55];
	add.f32 	%f57, %f56, %f56;
	ld.global.nc.f32 	%f58, [%rd49];
	ld.global.nc.f32 	%f59, [%rd50];
	mul.f32 	%f60, %f59, %f2;
	fma.rn.f32 	%f61, %f58, %f1, %f60;
	ld.global.nc.f32 	%f62, [%rd51];
	fma.rn.f32 	%f63, %f62, %f3, %f61;
	ld.global.nc.f32 	%f64, [%rd54];
	fma.rn.f32 	%f65, %f57, %f63, %f64;
	mul.f32 	%f66, %f65, %f29;
	fma.rn.f32 	%f13, %f66, %f58, %f10;
	fma.rn.f32 	%f14, %f66, %f59, %f11;
	fma.rn.f32 	%f15, %f66, %f62, %f12;
	add.s32 	%r19, %r2, 1;
	and.b16  	%rs9, %rs2, 255;
	setp.eq.s16	%p10, %rs9, 0;
	@%p10 bra 	BB5_13;

	rem.s32 	%r71, %r19, %r32;
	add.s32 	%r72, %r71, %r32;
	rem.s32 	%r101, %r72, %r32;
	bra.uni 	BB5_14;

BB5_13:
	add.s32 	%r73, %r32, -1;
	min.s32 	%r101, %r19, %r73;

BB5_14:
	add.s32 	%r74, %r101, %r4;
	mad.lo.s32 	%r75, %r74, %r31, %r1;
	cvt.s64.s32	%rd56, %r75;
	mul.wide.s32 	%rd57, %r75, 4;
	add.s64 	%rd58, %rd6, %rd57;
	add.s64 	%rd59, %rd5, %rd57;
	add.s64 	%rd60, %rd4, %rd57;
	add.s64 	%rd61, %rd3, %rd56;
	ld.global.nc.u8 	%rs10, [%rd61];
	cvt.u32.u16	%r76, %rs10;
	and.b32  	%r77, %r76, 255;
	shl.b32 	%r78, %r77, 8;
	add.s32 	%r79, %r78, %r6;
	mul.wide.s32 	%rd62, %r79, 4;
	add.s64 	%rd63, %rd2, %rd62;
	add.s64 	%rd64, %rd1, %rd62;
	ld.global.nc.f32 	%f67, [%rd64];
	add.f32 	%f68, %f67, %f67;
	ld.global.nc.f32 	%f69, [%rd58];
	ld.global.nc.f32 	%f70, [%rd59];
	mul.f32 	%f71, %f70, %f2;
	fma.rn.f32 	%f72, %f69, %f1, %f71;
	ld.global.nc.f32 	%f73, [%rd60];
	fma.rn.f32 	%f74, %f73, %f3, %f72;
	ld.global.nc.f32 	%f75, [%rd63];
	fma.rn.f32 	%f76, %f68, %f74, %f75;
	mul.f32 	%f77, %f76, %f29;
	fma.rn.f32 	%f100, %f77, %f69, %f13;
	fma.rn.f32 	%f101, %f77, %f70, %f14;
	fma.rn.f32 	%f102, %f77, %f73, %f15;
	setp.eq.s32	%p11, %r33, 1;
	@%p11 bra 	BB5_22;

	and.b16  	%rs3, %rs4, 4;
	setp.eq.s16	%p12, %rs3, 0;
	add.s32 	%r23, %r3, -1;
	@%p12 bra 	BB5_17;

	rem.s32 	%r80, %r23, %r33;
	add.s32 	%r81, %r80, %r33;
	rem.s32 	%r102, %r81, %r33;
	bra.uni 	BB5_18;

BB5_17:
	mov.u32 	%r82, 0;
	max.s32 	%r102, %r23, %r82;

BB5_18:
	mad.lo.s32 	%r83, %r102, %r32, %r2;
	mad.lo.s32 	%r84, %r83, %r31, %r1;
	cvt.s64.s32	%rd65, %r84;
	mul.wide.s32 	%rd66, %r84, 4;
	add.s64 	%rd67, %rd6, %rd66;
	add.s64 	%rd68, %rd5, %rd66;
	add.s64 	%rd69, %rd4, %rd66;
	add.s64 	%rd70, %rd3, %rd65;
	ld.global.nc.u8 	%rs11, [%rd70];
	cvt.u32.u16	%r85, %rs11;
	and.b32  	%r86, %r85, 255;
	shl.b32 	%r87, %r86, 8;
	add.s32 	%r88, %r87, %r6;
	mul.wide.s32 	%rd71, %r88, 4;
	add.s64 	%rd72, %rd2, %rd71;
	add.s64 	%rd73, %rd1, %rd71;
	ld.global.nc.f32 	%f78, [%rd73];
	add.f32 	%f79, %f78, %f78;
	ld.global.nc.f32 	%f80, [%rd67];
	ld.global.nc.f32 	%f81, [%rd68];
	mul.f32 	%f82, %f81, %f2;
	fma.rn.f32 	%f83, %f80, %f1, %f82;
	ld.global.nc.f32 	%f84, [%rd69];
	fma.rn.f32 	%f85, %f84, %f3, %f83;
	ld.global.nc.f32 	%f86, [%rd72];
	fma.rn.f32 	%f87, %f79, %f85, %f86;
	mul.f32 	%f88, %f87, %f30;
	fma.rn.f32 	%f19, %f88, %f80, %f100;
	fma.rn.f32 	%f20, %f88, %f81, %f101;
	fma.rn.f32 	%f21, %f88, %f84, %f102;
	add.s32 	%r27, %r3, 1;
	and.b16  	%rs12, %rs3, 255;
	setp.eq.s16	%p13, %rs12, 0;
	@%p13 bra 	BB5_20;

	rem.s32 	%r89, %r27, %r33;
	add.s32 	%r90, %r89, %r33;
	rem.s32 	%r103, %r90, %r33;
	bra.uni 	BB5_21;

BB5_20:
	add.s32 	%r91, %r33, -1;
	min.s32 	%r103, %r27, %r91;

BB5_21:
	mad.lo.s32 	%r92, %r103, %r32, %r2;
	mad.lo.s32 	%r93, %r92, %r31, %r1;
	cvt.s64.s32	%rd74, %r93;
	mul.wide.s32 	%rd75, %r93, 4;
	add.s64 	%rd76, %rd6, %rd75;
	add.s64 	%rd77, %rd5, %rd75;
	add.s64 	%rd78, %rd4, %rd75;
	add.s64 	%rd79, %rd3, %rd74;
	ld.global.nc.u8 	%rs13, [%rd79];
	cvt.u32.u16	%r94, %rs13;
	and.b32  	%r95, %r94, 255;
	shl.b32 	%r96, %r95, 8;
	add.s32 	%r97, %r96, %r6;
	mul.wide.s32 	%rd80, %r97, 4;
	add.s64 	%rd81, %rd2, %rd80;
	add.s64 	%rd82, %rd1, %rd80;
	ld.global.nc.f32 	%f89, [%rd82];
	add.f32 	%f90, %f89, %f89;
	ld.global.nc.f32 	%f91, [%rd76];
	ld.global.nc.f32 	%f92, [%rd77];
	mul.f32 	%f93, %f92, %f2;
	fma.rn.f32 	%f94, %f91, %f1, %f93;
	ld.global.nc.f32 	%f95, [%rd78];
	fma.rn.f32 	%f96, %f95, %f3, %f94;
	ld.global.nc.f32 	%f97, [%rd81];
	fma.rn.f32 	%f98, %f90, %f96, %f97;
	mul.f32 	%f99, %f98, %f30;
	fma.rn.f32 	%f100, %f99, %f91, %f19;
	fma.rn.f32 	%f101, %f99, %f92, %f20;
	fma.rn.f32 	%f102, %f99, %f95, %f21;

BB5_22:
	st.global.f32 	[%rd8], %f100;
	st.global.f32 	[%rd9], %f101;
	st.global.f32 	[%rd10], %f102;

BB5_23:
	ret;
}


`
	addiecexchange_ptx_50 = `
.version 4.1
.target sm_50
.address_size 64


.weak .func  (.param .b32 func_retval0) cudaMalloc(
	.param .b64 cudaMalloc_param_0,
	.param .b64 cudaMalloc_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaFuncGetAttributes(
	.param .b64 cudaFuncGetAttributes_param_0,
	.param .b64 cudaFuncGetAttributes_param_1
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaDeviceGetAttribute(
	.param .b64 cudaDeviceGetAttribute_param_0,
	.param .b32 cudaDeviceGetAttribute_param_1,
	.param .b32 cudaDeviceGetAttribute_param_2
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaGetDevice(
	.param .b64 cudaGetDevice_param_0
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.weak .func  (.param .b32 func_retval0) cudaOccupancyMaxActiveBlocksPerMultiprocessor(
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_0,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_1,
	.param .b32 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_2,
	.param .b64 cudaOccupancyMaxActiveBlocksPerMultiprocessor_param_3
)
{
	.reg .s32 	%r<2>;


	mov.u32 	%r1, 30;
	st.param.b32	[func_retval0+0], %r1;
	ret;
}

.visible .entry addiecexchange(
	.param .u64 addiecexchange_param_0,
	.param .u64 addiecexchange_param_1,
	.param .u64 addiecexchange_param_2,
	.param .u64 addiecexchange_param_3,
	.param .u64 addiecexchange_param_4,
	.param .u64 addiecexchange_param_5,
	.param .u64 addiecexchange_param_6,
	.param .u64 addiecexchange_param_7,
	.param .u64 addiecexchange_param_8,
	.param .f32 addiecexchange_param_9,
	.param .f32 addiecexchange_param_10,
	.param .f32 addiecexchange_param_11,
	.param .u32 addiecexchange_param_12,
	.param .u32 addiecexchange_param_13,
	.param .u32 addiecexchange_param_14,
	.param .u8 addiecexchange_param_15
)
{
	.reg .pred 	%p<14>;
	.reg .s16 	%rs<14>;
	.reg .s32 	%r<104>;
	.reg .f32 	%f<103>;
	.reg .s64 	%rd<83>;


	ld.param.u64 	%rd11, [addiecexchange_param_0];
	ld.param.u64 	%rd12, [addiecexchange_param_1];
	ld.param.u64 	%rd13, [addiecexchange_param_2];
	ld.param.u64 	%rd14, [addiecexchange_param_3];
	ld.param.u64 	%rd15, [addiecexchange_param_4];
	ld.param.u64 	%rd16, [addiecexchange_param_5];
	ld.param.u64 	%rd17, [addiecexchange_param_6];
	ld.param.u64 	%rd18, [addiecexchange_param_7];
	ld.param.u64 	%rd19, [addiecexchange_param_8];
	ld.param.f32 	%f28, [addiecexchange_param_9];
	ld.param.f32 	%f29, [addiecexchange_param_10];
	ld.param.f32 	%f30, [addiecexchange_param_11];
	ld.param.u32 	%r31, [addiecexchange_param_12];
	ld.param.u32 	%r32, [addiecexchange_param_13];
	ld.param.u32 	%r33, [addiecexchange_param_14];
	ld.param.u8 	%rs4, [addiecexchange_param_15];
	cvta.to.global.u64 	%rd1, %rd18;
	cvta.to.global.u64 	%rd2, %rd17;
	cvta.to.global.u64 	%rd3, %rd19;
	cvta.to.global.u64 	%rd4, %rd16;
	cvta.to.global.u64 	%rd5, %rd15;
	cvta.to.global.u64 	%rd6, %rd14;
	mov.u32 	%r34, %ntid.x;
	mov.u32 	%r35, %ctaid.x;
	mov.u32 	%r36, %tid.x;
	mad.lo.s32 	%r1, %r34, %r35, %r36;
	mov.u32 	%r37, %ntid.y;
	mov.u32 	%r38, %ctaid.y;
	mov.u32 	%r39, %tid.y;
	mad.lo.s32 	%r2, %r37, %r38, %r39;
	mov.u32 	%r40, %ntid.z;
	mov.u32 	%r41, %ctaid.z;
	mov.u32 	%r42, %tid.z;
	mad.lo.s32 	%r3, %r40, %r41, %r42;
	setp.ge.s32	%p1, %r2, %r32;
	setp.ge.s32	%p2, %r1, %r31;
	or.pred  	%p3, %p2, %p1;
	setp.ge.s32	%p4, %r3, %r33;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB5_23;

	mul.lo.s32 	%r4, %r3, %r32;
	add.s32 	%r43, %r4, %r2;
	mul.lo.s32 	%r5, %r43, %r31;
	add.s32 	%r44, %r5, %r1;
	cvt.s64.s32	%rd7, %r44;
	mul.wide.s32 	%rd20, %r44, 4;
	add.s64 	%rd21, %rd6, %rd20;
	add.s64 	%rd22, %rd5, %rd20;
	add.s64 	%rd23, %rd4, %rd20;
	ld.global.nc.f32 	%f1, [%rd21];
	ld.global.nc.f32 	%f2, [%rd22];
	mul.f32 	%f31, %f2, %f2;
	fma.rn.f32 	%f32, %f1, %f1, %f31;
	ld.global.nc.f32 	%f3, [%rd23];
	fma.rn.f32 	%f33, %f3, %f3, %f32;
	setp.eq.f32	%p6, %f33, 0f00000000;
	@%p6 bra 	BB5_23;

	cvta.to.global.u64 	%rd24, %rd13;
	cvta.to.global.u64 	%rd25, %rd12;
	cvta.to.global.u64 	%rd26, %rd11;
	add.s64 	%rd27, %rd3, %rd7;
	ld.global.nc.u8 	%rs5, [%rd27];
	cvt.u32.u16	%r45, %rs5;
	and.b32  	%r6, %r45, 255;
	shl.b64 	%rd28, %rd7, 2;
	add.s64 	%rd8, %rd26, %rd28;
	ld.global.f32 	%f4, [%rd8];
	add.s64 	%rd9, %rd25, %rd28;
	ld.global.f32 	%f5, [%rd9];
	add.s64 	%rd10, %rd24, %rd28;
	ld.global.f32 	%f6, [%rd10];
	add.s32 	%r7, %r1, -1;
	and.b16  	%rs1, %rs4, 1;
	setp.eq.b16	%p7, %rs1, 1;
	@!%p7 bra 	BB5_4;
	bra.uni 	BB5_3;

BB5_3:
	rem.s32 	%r46, %r7, %r31;
	add.s32 	%r47, %r46, %r31;
	rem.s32 	%r98, %r47, %r31;
	bra.uni 	BB5_5;

BB5_4:
	mov.u32 	%r48, 0;
	max.s32 	%r98, %r7, %r48;

BB5_5:
	add.s32 	%r49, %r98, %r5;
	cvt.s64.s32	%rd29, %r49;
	mul.wide.s32 	%rd30, %r49, 4;
	add.s64 	%rd31, %rd6, %rd30;
	add.s64 	%rd32, %rd5, %rd30;
	add.s64 	%rd33, %rd4, %rd30;
	add.s64 	%rd34, %rd3, %rd29;
	ld.global.nc.u8 	%rs6, [%rd34];
	cvt.u32.u16	%r50, %rs6;
	and.b32  	%r51, %r50, 255;
	shl.b32 	%r52, %r51, 8;
	add.s32 	%r53, %r52, %r6;
	mul.wide.s32 	%rd35, %r53, 4;
	add.s64 	%rd36, %rd2, %rd35;
	add.s64 	%rd37, %rd1, %rd35;
	ld.global.nc.f32 	%f34, [%rd37];
	add.f32 	%f35, %f34, %f34;
	ld.global.nc.f32 	%f36, [%rd31];
	ld.global.nc.f32 	%f37, [%rd32];
	mul.f32 	%f38, %f37, %f2;
	fma.rn.f32 	%f39, %f36, %f1, %f38;
	ld.global.nc.f32 	%f40, [%rd33];
	fma.rn.f32 	%f41, %f40, %f3, %f39;
	ld.global.nc.f32 	%f42, [%rd36];
	fma.rn.f32 	%f43, %f35, %f41, %f42;
	mul.f32 	%f44, %f43, %f28;
	fma.rn.f32 	%f7, %f44, %f36, %f4;
	fma.rn.f32 	%f8, %f44, %f37, %f5;
	fma.rn.f32 	%f9, %f44, %f40, %f6;
	add.s32 	%r11, %r1, 1;
	setp.eq.s16	%p8, %rs1, 0;
	@%p8 bra 	BB5_7;

	rem.s32 	%r54, %r11, %r31;
	add.s32 	%r55, %r54, %r31;
	rem.s32 	%r99, %r55, %r31;
	bra.uni 	BB5_8;

BB5_7:
	add.s32 	%r56, %r31, -1;
	min.s32 	%r99, %r11, %r56;

BB5_8:
	add.s32 	%r57, %r99, %r5;
	cvt.s64.s32	%rd38, %r57;
	mul.wide.s32 	%rd39, %r57, 4;
	add.s64 	%rd40, %rd6, %rd39;
	add.s64 	%rd41, %rd5, %rd39;
	add.s64 	%rd42, %rd4, %rd39;
	add.s64 	%rd43, %rd3, %rd38;
	ld.global.nc.u8 	%rs7, [%rd43];
	cvt.u32.u16	%r58, %rs7;
	and.b32  	%r59, %r58, 255;
	shl.b32 	%r60, %r59, 8;
	add.s32 	%r61, %r60, %r6;
	mul.wide.s32 	%rd44, %r61, 4;
	add.s64 	%rd45, %rd2, %rd44;
	add.s64 	%rd46, %rd1, %rd44;
	ld.global.nc.f32 	%f45, [%rd46];
	add.f32 	%f46, %f45, %f45;
	ld.global.nc.f32 	%f47, [%rd40];
	ld.global.nc.f32 	%f48, [%rd41];
	mul.f32 	%f49, %f48, %f2;
	fma.rn.f32 	%f50, %f47, %f1, %f49;
	ld.global.nc.f32 	%f51, [%rd42];
	fma.rn.f32 	%f52, %f51, %f3, %f50;
	ld.global.nc.f32 	%f53, [%rd45];
	fma.rn.f32 	%f54, %f46, %f52, %f53;
	mul.f32 	%f55, %f54, %f28;
	fma.rn.f32 	%f10, %f55, %f47, %f7;
	fma.rn.f32 	%f11, %f55, %f48, %f8;
	fma.rn.f32 	%f12, %f55, %f51, %f9;
	and.b16  	%rs2, %rs4, 2;
	setp.eq.s16	%p9, %rs2, 0;
	add.s32 	%r15, %r2, -1;
	@%p9 bra 	BB5_10;

	rem.s32 	%r62, %r15, %r32;
	add.s32 	%r63, %r62, %r32;
	rem.s32 	%r100, %r63, %r32;
	bra.uni 	BB5_11;

BB5_10:
	mov.u32 	%r64, 0;
	max.s32 	%r100, %r15, %r64;

BB5_11:
	add.s32 	%r65, %r100, %r4;
	mad.lo.s32 	%r66, %r65, %r31, %r1;
	cvt.s64.s32	%rd47, %r66;
	mul.wide.s32 	%rd48, %r66, 4;
	add.s64 	%rd49, %rd6, %rd48;
	add.s64 	%rd50, %rd5, %rd48;
	add.s64 	%rd51, %rd4, %rd48;
	add.s64 	%rd52, %rd3, %rd47;
	ld.global.nc.u8 	%rs8, [%rd52];
	cvt.u32.u16	%r67, %rs8;
	and.b32  	%r68, %r67, 255;
	shl.b32 	%r69, %r68, 8;
	add.s32 	%r70, %r69, %r6;
	mul.wide.s32 	%rd53, %r70, 4;
	add.s64 	%rd54, %rd2, %rd53;
	add.s64 	%rd55, %rd1, %rd53;
	ld.global.nc.f32 	%f56, [%rd55];
	add.f32 	%f57, %f56, %f56;
	ld.global.nc.f32 	%f58, [%rd49];
	ld.global.nc.f32 	%f59, [%rd50];
	mul.f32 	%f60, %f59, %f2;
	fma.rn.f32 	%f61, %f58, %f1, %f60;
	ld.global.nc.f32 	%f62, [%rd51];
	fma.rn.f32 	%f63, %f62, %f3, %f61;
	ld.global.nc.f32 	%f64, [%rd54];
	fma.rn.f32 	%f65, %f57, %f63, %f64;
	mul.f32 	%f66, %f65, %f29;
	fma.rn.f32 	%f13, %f66, %f58, %f10;
	fma.rn.f32 	%f14, %f66, %f59, %f11;
	fma.rn.f32 	%f15, %f66, %f62, %f12;
	add.s32 	%r19, %r2, 1;
	and.b16  	%rs9, %rs2, 255;
	setp.eq.s16	%p10, %rs9, 0;
	@%p10 bra 	BB5_13;

	rem.s32 	%r71, %r19, %r32;
	add.s32 	%r72, %r71, %r32;
	rem.s32 	%r101, %r72, %r32;
	bra.uni 	BB5_14;

BB5_13:
	add.s32 	%r73, %r32, -1;
	min.s32 	%r101, %r19, %r73;

BB5_14:
	add.s32 	%r74, %r101, %r4;
	mad.lo.s32 	%r75, %r74, %r31, %r1;
	cvt.s64.s32	%rd56, %r75;
	mul.wide.s32 	%rd57, %r75, 4;
	add.s64 	%rd58, %rd6, %rd57;
	add.s64 	%rd59, %rd5, %rd57;
	add.s64 	%rd60, %rd4, %rd57;
	add.s64 	%rd61, %rd3, %rd56;
	ld.global.nc.u8 	%rs10, [%rd61];
	cvt.u32.u16	%r76, %rs10;
	and.b32  	%r77, %r76, 255;
	shl.b32 	%r78, %r77, 8;
	add.s32 	%r79, %r78, %r6;
	mul.wide.s32 	%rd62, %r79, 4;
	add.s64 	%rd63, %rd2, %rd62;
	add.s64 	%rd64, %rd1, %rd62;
	ld.global.nc.f32 	%f67, [%rd64];
	add.f32 	%f68, %f67, %f67;
	ld.global.nc.f32 	%f69, [%rd58];
	ld.global.nc.f32 	%f70, [%rd59];
	mul.f32 	%f71, %f70, %f2;
	fma.rn.f32 	%f72, %f69, %f1, %f71;
	ld.global.nc.f32 	%f73, [%rd60];
	fma.rn.f32 	%f74, %f73, %f3, %f72;
	ld.global.nc.f32 	%f75, [%rd63];
	fma.rn.f32 	%f76, %f68, %f74, %f75;
	mul.f32 	%f77, %f76, %f29;
	fma.rn.f32 	%f100, %f77, %f69, %f13;
	fma.rn.f32 	%f101, %f77, %f70, %f14;
	fma.rn.f32 	%f102, %f77, %f73, %f15;
	setp.eq.s32	%p11, %r33, 1;
	@%p11 bra 	BB5_22;

	and.b16  	%rs3, %rs4, 4;
	setp.eq.s16	%p12, %rs3, 0;
	add.s32 	%r23, %r3, -1;
	@%p12 bra 	BB5_17;

	rem.s32 	%r80, %r23, %r33;
	add.s32 	%r81, %r80, %r33;
	rem.s32 	%r102, %r81, %r33;
	bra.uni 	BB5_18;

BB5_17:
	mov.u32 	%r82, 0;
	max.s32 	%r102, %r23, %r82;

BB5_18:
	mad.lo.s32 	%r83, %r102, %r32, %r2;
	mad.lo.s32 	%r84, %r83, %r31, %r1;
	cvt.s64.s32	%rd65, %r84;
	mul.wide.s32 	%rd66, %r84, 4;
	add.s64 	%rd67, %rd6, %rd66;
	add.s64 	%rd68, %rd5, %rd66;
	add.s64 	%rd69, %rd4, %rd66;
	add.s64 	%rd70, %rd3, %rd65;
	ld.global.nc.u8 	%rs11, [%rd70];
	cvt.u32.u16	%r85, %rs11;
	and.b32  	%r86, %r85, 255;
	shl.b32 	%r87, %r86, 8;
	add.s32 	%r88, %r87, %r6;
	mul.wide.s32 	%rd71, %r88, 4;
	add.s64 	%rd72, %rd2, %rd71;
	add.s64 	%rd73, %rd1, %rd71;
	ld.global.nc.f32 	%f78, [%rd73];
	add.f32 	%f79, %f78, %f78;
	ld.global.nc.f32 	%f80, [%rd67];
	ld.global.nc.f32 	%f81, [%rd68];
	mul.f32 	%f82, %f81, %f2;
	fma.rn.f32 	%f83, %f80, %f1, %f82;
	ld.global.nc.f32 	%f84, [%rd69];
	fma.rn.f32 	%f85, %f84, %f3, %f83;
	ld.global.nc.f32 	%f86, [%rd72];
	fma.rn.f32 	%f87, %f79, %f85, %f86;
	mul.f32 	%f88, %f87, %f30;
	fma.rn.f32 	%f19, %f88, %f80, %f100;
	fma.rn.f32 	%f20, %f88, %f81, %f101;
	fma.rn.f32 	%f21, %f88, %f84, %f102;
	add.s32 	%r27, %r3, 1;
	and.b16  	%rs12, %rs3, 255;
	setp.eq.s16	%p13, %rs12, 0;
	@%p13 bra 	BB5_20;

	rem.s32 	%r89, %r27, %r33;
	add.s32 	%r90, %r89, %r33;
	rem.s32 	%r103, %r90, %r33;
	bra.uni 	BB5_21;

BB5_20:
	add.s32 	%r91, %r33, -1;
	min.s32 	%r103, %r27, %r91;

BB5_21:
	mad.lo.s32 	%r92, %r103, %r32, %r2;
	mad.lo.s32 	%r93, %r92, %r31, %r1;
	cvt.s64.s32	%rd74, %r93;
	mul.wide.s32 	%rd75, %r93, 4;
	add.s64 	%rd76, %rd6, %rd75;
	add.s64 	%rd77, %rd5, %rd75;
	add.s64 	%rd78, %rd4, %rd75;
	add.s64 	%rd79, %rd3, %rd74;
	ld.global.nc.u8 	%rs13, [%rd79];
	cvt.u32.u16	%r94, %rs13;
	and.b32  	%r95, %r94, 255;
	shl.b32 	%r96, %r95, 8;
	add.s32 	%r97, %r96, %r6;
	mul.wide.s32 	%rd80, %r97, 4;
	add.s64 	%rd81, %rd2, %rd80;
	add.s64 	%rd82, %rd1, %rd80;
	ld.global.nc.f32 	%f89, [%rd82];
	add.f32 	%f90, %f89, %f89;
	ld.global.nc.f32 	%f91, [%rd76];
	ld.global.nc.f32 	%f92, [%rd77];
	mul.f32 	%f93, %f92, %f2;
	fma.rn.f32 	%f94, %f91, %f1, %f93;
	ld.global.nc.f32 	%f95, [%rd78];
	fma.rn.f32 	%f96, %f95, %f3, %f94;
	ld.global.nc.f32 	%f97, [%rd81];
	fma.rn.f32 	%f98, %f90, %f96, %f97;
	mul.f32 	%f99, %f98, %f30;
	fma.rn.f32 	%f100, %f99, %f91, %f19;
	fma.rn.f32 	%f101, %f99, %f92, %f20;
	fma.rn.f32 	%f102, %f99, %f95, %f21;

BB5_22:
	st.global.f32 	[%rd8], %f100;
	st.global.f32 	[%rd9], %f101;
	st.global.f32 	[%rd10], %f102;

BB5_23:
	ret;
}


`
)
